/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tonito;

import javax.swing.ImageIcon;



/**
 *
 * @author Federico Teixeira G
 */
public class AyudaFrame extends javax.swing.JFrame {
    private HojaMusical music;
    /**
     * Creates new form OpcionesFrame
     */
    public AyudaFrame() {
        initComponents();
        setTitle("TonUDO");
        setIconImage(new ImageIcon(getClass().getResource("TonUDOiconoblack-01.png")).getImage());
        setLocationRelativeTo(null);
        setResizable(false);
    }
    public AyudaFrame(HojaMusical cancion) {
        music=cancion;
        initComponents();
        setTitle("TonUDO");
        setIconImage(new ImageIcon(getClass().getResource("TonUDOiconoblack-01.png")).getImage());
        setLocationRelativeTo(null);
        setResizable(false);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBarraIzq = new javax.swing.JPanel();
        lOpciones = new javax.swing.JLabel();
        panelSalirmenu = new javax.swing.JPanel();
        lSalir = new javax.swing.JLabel();
        panelcrearhojamenu = new javax.swing.JPanel();
        lCrearhoja = new javax.swing.JLabel();
        paneltransportarmenu = new javax.swing.JPanel();
        lTransportarhoja = new javax.swing.JLabel();
        paneleditarmenu = new javax.swing.JPanel();
        lEditarhoja = new javax.swing.JLabel();
        paneleliminarmenu = new javax.swing.JPanel();
        lEliminarhoja = new javax.swing.JLabel();
        panelcambioautormenu = new javax.swing.JPanel();
        lCambiarelautor = new javax.swing.JLabel();
        panelcambiocancionmenu = new javax.swing.JPanel();
        lCambiarnomcancion = new javax.swing.JLabel();
        panelporcapasayuda = new javax.swing.JLayeredPane();
        panelhojanueva = new javax.swing.JPanel();
        lPasoscrear = new javax.swing.JLabel();
        scrollpanepasoscrear = new javax.swing.JScrollPane();
        tapasoscrear = new javax.swing.JTextArea();
        paneltransportarhoja = new javax.swing.JPanel();
        scrollpanepasostransportar = new javax.swing.JScrollPane();
        tapasostransportar = new javax.swing.JTextArea();
        lpasostransportar = new javax.swing.JLabel();
        paneleditarhoja = new javax.swing.JPanel();
        scrollpanepasoseditar = new javax.swing.JScrollPane();
        tapasoseditar = new javax.swing.JTextArea();
        lpasoseditar = new javax.swing.JLabel();
        paneleliminarhoja = new javax.swing.JPanel();
        scrollpanepasoseliminar = new javax.swing.JScrollPane();
        tapasoseliminar = new javax.swing.JTextArea();
        lpasoseliminar = new javax.swing.JLabel();
        panelcambiarautor = new javax.swing.JPanel();
        scrollpanepasoscambioautor = new javax.swing.JScrollPane();
        tapasoscambioautor = new javax.swing.JTextArea();
        lpasoscambioautor = new javax.swing.JLabel();
        panelcambiarcancion = new javax.swing.JPanel();
        scrollpanepasoscambiocancion = new javax.swing.JScrollPane();
        tapasoscambiocancion = new javax.swing.JTextArea();
        lpasoscambiocancion = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelBarraIzq.setBackground(new java.awt.Color(0, 102, 0));

        lOpciones.setFont(new java.awt.Font("Segoe UI Light", 0, 36)); // NOI18N
        lOpciones.setForeground(new java.awt.Color(255, 255, 255));
        lOpciones.setText("Ayuda");

        panelSalirmenu.setBackground(new java.awt.Color(204, 204, 204));
        panelSalirmenu.setPreferredSize(new java.awt.Dimension(133, 47));
        panelSalirmenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelSalirmenuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelSalirmenuMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelSalirmenuMousePressed(evt);
            }
        });

        lSalir.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lSalir.setForeground(new java.awt.Color(0, 0, 0));
        lSalir.setText("Salir");

        javax.swing.GroupLayout panelSalirmenuLayout = new javax.swing.GroupLayout(panelSalirmenu);
        panelSalirmenu.setLayout(panelSalirmenuLayout);
        panelSalirmenuLayout.setHorizontalGroup(
            panelSalirmenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSalirmenuLayout.createSequentialGroup()
                .addContainerGap(51, Short.MAX_VALUE)
                .addComponent(lSalir)
                .addGap(49, 49, 49))
        );
        panelSalirmenuLayout.setVerticalGroup(
            panelSalirmenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSalirmenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lSalir)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelcrearhojamenu.setBackground(new java.awt.Color(0, 102, 0));
        panelcrearhojamenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelcrearhojamenuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelcrearhojamenuMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelcrearhojamenuMousePressed(evt);
            }
        });

        lCrearhoja.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        lCrearhoja.setForeground(new java.awt.Color(255, 255, 255));
        lCrearhoja.setText("Crear una hoja nueva");

        javax.swing.GroupLayout panelcrearhojamenuLayout = new javax.swing.GroupLayout(panelcrearhojamenu);
        panelcrearhojamenu.setLayout(panelcrearhojamenuLayout);
        panelcrearhojamenuLayout.setHorizontalGroup(
            panelcrearhojamenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelcrearhojamenuLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(lCrearhoja)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelcrearhojamenuLayout.setVerticalGroup(
            panelcrearhojamenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lCrearhoja)
        );

        paneltransportarmenu.setBackground(new java.awt.Color(0, 102, 0));
        paneltransportarmenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                paneltransportarmenuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                paneltransportarmenuMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                paneltransportarmenuMousePressed(evt);
            }
        });

        lTransportarhoja.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        lTransportarhoja.setForeground(new java.awt.Color(255, 255, 255));
        lTransportarhoja.setText("Transportar una hoja");

        javax.swing.GroupLayout paneltransportarmenuLayout = new javax.swing.GroupLayout(paneltransportarmenu);
        paneltransportarmenu.setLayout(paneltransportarmenuLayout);
        paneltransportarmenuLayout.setHorizontalGroup(
            paneltransportarmenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneltransportarmenuLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(lTransportarhoja)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        paneltransportarmenuLayout.setVerticalGroup(
            paneltransportarmenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneltransportarmenuLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lTransportarhoja))
        );

        paneleditarmenu.setBackground(new java.awt.Color(0, 102, 0));
        paneleditarmenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                paneleditarmenuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                paneleditarmenuMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                paneleditarmenuMousePressed(evt);
            }
        });

        lEditarhoja.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        lEditarhoja.setForeground(new java.awt.Color(255, 255, 255));
        lEditarhoja.setText("Editar una hoja");

        javax.swing.GroupLayout paneleditarmenuLayout = new javax.swing.GroupLayout(paneleditarmenu);
        paneleditarmenu.setLayout(paneleditarmenuLayout);
        paneleditarmenuLayout.setHorizontalGroup(
            paneleditarmenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneleditarmenuLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(lEditarhoja)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        paneleditarmenuLayout.setVerticalGroup(
            paneleditarmenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lEditarhoja)
        );

        paneleliminarmenu.setBackground(new java.awt.Color(0, 102, 0));
        paneleliminarmenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                paneleliminarmenuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                paneleliminarmenuMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                paneleliminarmenuMousePressed(evt);
            }
        });

        lEliminarhoja.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        lEliminarhoja.setForeground(new java.awt.Color(255, 255, 255));
        lEliminarhoja.setText("Eliminar una hoja");

        javax.swing.GroupLayout paneleliminarmenuLayout = new javax.swing.GroupLayout(paneleliminarmenu);
        paneleliminarmenu.setLayout(paneleliminarmenuLayout);
        paneleliminarmenuLayout.setHorizontalGroup(
            paneleliminarmenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneleliminarmenuLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(lEliminarhoja)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        paneleliminarmenuLayout.setVerticalGroup(
            paneleliminarmenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneleliminarmenuLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lEliminarhoja))
        );

        panelcambioautormenu.setBackground(new java.awt.Color(0, 102, 0));
        panelcambioautormenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelcambioautormenuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelcambioautormenuMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelcambioautormenuMousePressed(evt);
            }
        });

        lCambiarelautor.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        lCambiarelautor.setForeground(new java.awt.Color(255, 255, 255));
        lCambiarelautor.setText("Cambiar el autor");

        javax.swing.GroupLayout panelcambioautormenuLayout = new javax.swing.GroupLayout(panelcambioautormenu);
        panelcambioautormenu.setLayout(panelcambioautormenuLayout);
        panelcambioautormenuLayout.setHorizontalGroup(
            panelcambioautormenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelcambioautormenuLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(lCambiarelautor)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelcambioautormenuLayout.setVerticalGroup(
            panelcambioautormenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelcambioautormenuLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lCambiarelautor))
        );

        panelcambiocancionmenu.setBackground(new java.awt.Color(0, 102, 0));
        panelcambiocancionmenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelcambiocancionmenuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelcambiocancionmenuMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelcambiocancionmenuMousePressed(evt);
            }
        });

        lCambiarnomcancion.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        lCambiarnomcancion.setForeground(new java.awt.Color(255, 255, 255));
        lCambiarnomcancion.setText("Cambiar el nombre de la canción");

        javax.swing.GroupLayout panelcambiocancionmenuLayout = new javax.swing.GroupLayout(panelcambiocancionmenu);
        panelcambiocancionmenu.setLayout(panelcambiocancionmenuLayout);
        panelcambiocancionmenuLayout.setHorizontalGroup(
            panelcambiocancionmenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelcambiocancionmenuLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(lCambiarnomcancion)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelcambiocancionmenuLayout.setVerticalGroup(
            panelcambiocancionmenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelcambiocancionmenuLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lCambiarnomcancion))
        );

        javax.swing.GroupLayout panelBarraIzqLayout = new javax.swing.GroupLayout(panelBarraIzq);
        panelBarraIzq.setLayout(panelBarraIzqLayout);
        panelBarraIzqLayout.setHorizontalGroup(
            panelBarraIzqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelcrearhojamenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(paneltransportarmenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(paneleditarmenu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(paneleliminarmenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelBarraIzqLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(lOpciones)
                .addContainerGap(140, Short.MAX_VALUE))
            .addComponent(panelcambioautormenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelcambiocancionmenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBarraIzqLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelSalirmenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70))
        );
        panelBarraIzqLayout.setVerticalGroup(
            panelBarraIzqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBarraIzqLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lOpciones)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelcrearhojamenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(paneltransportarmenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(paneleditarmenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(paneleliminarmenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(panelcambioautormenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(panelcambiocancionmenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 177, Short.MAX_VALUE)
                .addComponent(panelSalirmenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
        );

        panelporcapasayuda.setBackground(new java.awt.Color(255, 255, 255));

        panelhojanueva.setBackground(new java.awt.Color(255, 255, 255));

        lPasoscrear.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lPasoscrear.setText("Pasos para crear una hoja nueva");

        scrollpanepasoscrear.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        scrollpanepasoscrear.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        tapasoscrear.setColumns(20);
        tapasoscrear.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tapasoscrear.setLineWrap(true);
        tapasoscrear.setRows(5);
        tapasoscrear.setText("1.Seleccione la opción Nueva Hoja en el menú principal de la aplicación.\n\n2. Introduzca los acordes, en cifrado anglosajón, en el campo de texto bajo la etiqueta Acordes.\n\n3. Introduzca el nombre de la hoja (Ej. Coro).\n\n4. Seleccione el tono actual de la hoja creada.\n\n5. Presione el botón guardar.\n\n\n");
        tapasoscrear.setWrapStyleWord(true);
        tapasoscrear.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        tapasoscrear.setEnabled(false);
        scrollpanepasoscrear.setViewportView(tapasoscrear);

        javax.swing.GroupLayout panelhojanuevaLayout = new javax.swing.GroupLayout(panelhojanueva);
        panelhojanueva.setLayout(panelhojanuevaLayout);
        panelhojanuevaLayout.setHorizontalGroup(
            panelhojanuevaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelhojanuevaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelhojanuevaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelhojanuevaLayout.createSequentialGroup()
                        .addComponent(lPasoscrear)
                        .addGap(0, 161, Short.MAX_VALUE))
                    .addComponent(scrollpanepasoscrear))
                .addContainerGap())
        );
        panelhojanuevaLayout.setVerticalGroup(
            panelhojanuevaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelhojanuevaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lPasoscrear)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollpanepasoscrear, javax.swing.GroupLayout.DEFAULT_SIZE, 427, Short.MAX_VALUE)
                .addContainerGap())
        );

        paneltransportarhoja.setBackground(new java.awt.Color(255, 255, 255));

        scrollpanepasostransportar.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        scrollpanepasostransportar.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        tapasostransportar.setColumns(20);
        tapasostransportar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tapasostransportar.setLineWrap(true);
        tapasostransportar.setRows(5);
        tapasostransportar.setText("1.Seleccione la opción Ver Hojas en el menú principal de la aplicación.\n\n2. Seleccione la hoja que desea transportar en la lista de la derecha.\n\n3. Haga clic en el botón transportar que se encuentra debajo de la      lista.\n\n4. En la ventana que se acaba de abrir seleccione el tono al que desea transportar la hoja. Podrá ver como quedará la hoja transportada sin tener que guardar.\n\n5. Presione el botón guardar para modificar la hoja.\n\n*Recuerde que si no presiona el botón guardar no se realizarán los cambios a la hoja.\n\n**Solo puede transportar una hoja si ya la ha creado con la opción Nueva Hoja.\n\n\n");
        tapasostransportar.setWrapStyleWord(true);
        tapasostransportar.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        tapasostransportar.setEnabled(false);
        scrollpanepasostransportar.setViewportView(tapasostransportar);

        lpasostransportar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lpasostransportar.setText("Pasos para transportar una hoja");

        javax.swing.GroupLayout paneltransportarhojaLayout = new javax.swing.GroupLayout(paneltransportarhoja);
        paneltransportarhoja.setLayout(paneltransportarhojaLayout);
        paneltransportarhojaLayout.setHorizontalGroup(
            paneltransportarhojaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneltransportarhojaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(paneltransportarhojaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paneltransportarhojaLayout.createSequentialGroup()
                        .addComponent(lpasostransportar)
                        .addGap(0, 178, Short.MAX_VALUE))
                    .addComponent(scrollpanepasostransportar))
                .addContainerGap())
        );
        paneltransportarhojaLayout.setVerticalGroup(
            paneltransportarhojaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneltransportarhojaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lpasostransportar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollpanepasostransportar, javax.swing.GroupLayout.DEFAULT_SIZE, 427, Short.MAX_VALUE)
                .addContainerGap())
        );

        paneleditarhoja.setBackground(new java.awt.Color(255, 255, 255));

        scrollpanepasoseditar.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        scrollpanepasoseditar.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        tapasoseditar.setColumns(20);
        tapasoseditar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tapasoseditar.setLineWrap(true);
        tapasoseditar.setRows(5);
        tapasoseditar.setText("1.Seleccione la opción Ver Hojas en el menú principal de la aplicación.\n\n2. Seleccione la hoja que desea editar en la lista de la derecha.\n\n3. Haga clic en el botón editar que se encuentra debajo de la lista.\n\n4. En la ventana que se acaba de abrir podrá modificar los acordes, el nombre de la hoja y el tono actual de la hoja.\n\n5. Presione el botón guardar para modificar la hoja.\n\n*Recuerde que si no presiona el botón guardar no se realizarán los cambios a la hoja.\n\n**Solo puede editar una hoja si ya la ha creado con la opción Nueva Hoja.\n\n\n");
        tapasoseditar.setWrapStyleWord(true);
        tapasoseditar.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        tapasoseditar.setEnabled(false);
        scrollpanepasoseditar.setViewportView(tapasoseditar);

        lpasoseditar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lpasoseditar.setText("Pasos para editar una hoja");

        javax.swing.GroupLayout paneleditarhojaLayout = new javax.swing.GroupLayout(paneleditarhoja);
        paneleditarhoja.setLayout(paneleditarhojaLayout);
        paneleditarhojaLayout.setHorizontalGroup(
            paneleditarhojaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneleditarhojaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(paneleditarhojaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paneleditarhojaLayout.createSequentialGroup()
                        .addComponent(lpasoseditar)
                        .addGap(0, 206, Short.MAX_VALUE))
                    .addComponent(scrollpanepasoseditar))
                .addContainerGap())
        );
        paneleditarhojaLayout.setVerticalGroup(
            paneleditarhojaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneleditarhojaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lpasoseditar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollpanepasoseditar, javax.swing.GroupLayout.DEFAULT_SIZE, 427, Short.MAX_VALUE)
                .addContainerGap())
        );

        paneleliminarhoja.setBackground(new java.awt.Color(255, 255, 255));

        scrollpanepasoseliminar.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        scrollpanepasoseliminar.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        tapasoseliminar.setColumns(20);
        tapasoseliminar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tapasoseliminar.setLineWrap(true);
        tapasoseliminar.setRows(5);
        tapasoseliminar.setText("1.Seleccione la opción Ver Hojas en el menú principal de la aplicación.\n\n2. Seleccione la hoja que desea eliminar en la lista de la derecha.\n\n3. Haga clic en el botón eliminar que se encuentra debajo de la lista.\n\n4. Aparecerá un mensaje solicitando confirmación para eliminar, presione sí.\n\n\n\n");
        tapasoseliminar.setWrapStyleWord(true);
        tapasoseliminar.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        tapasoseliminar.setEnabled(false);
        scrollpanepasoseliminar.setViewportView(tapasoseliminar);

        lpasoseliminar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lpasoseliminar.setText("Pasos para eliminar una hoja");

        javax.swing.GroupLayout paneleliminarhojaLayout = new javax.swing.GroupLayout(paneleliminarhoja);
        paneleliminarhoja.setLayout(paneleliminarhojaLayout);
        paneleliminarhojaLayout.setHorizontalGroup(
            paneleliminarhojaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneleliminarhojaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(paneleliminarhojaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paneleliminarhojaLayout.createSequentialGroup()
                        .addComponent(lpasoseliminar)
                        .addGap(0, 204, Short.MAX_VALUE))
                    .addComponent(scrollpanepasoseliminar))
                .addContainerGap())
        );
        paneleliminarhojaLayout.setVerticalGroup(
            paneleliminarhojaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneleliminarhojaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lpasoseliminar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollpanepasoseliminar, javax.swing.GroupLayout.DEFAULT_SIZE, 427, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelcambiarautor.setBackground(new java.awt.Color(255, 255, 255));
        panelcambiarautor.setForeground(new java.awt.Color(153, 153, 0));

        scrollpanepasoscambioautor.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        scrollpanepasoscambioautor.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        tapasoscambioautor.setColumns(20);
        tapasoscambioautor.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tapasoscambioautor.setLineWrap(true);
        tapasoscambioautor.setRows(5);
        tapasoscambioautor.setText("1.Seleccione la opción Opciones en el menú principal de la aplicación.\n\n2. En la casilla debajo de la etiqueta modificar autor introduzca el nombre del autor.\n\n3. Haga clic en el botón guardar.\n\n*Si una de las casillas está vacía se le notificará que no se pueden dejar los campos vacíos. \n\n**Por defecto el nombre del autor está vacío.\n\n");
        tapasoscambioautor.setWrapStyleWord(true);
        tapasoscambioautor.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        tapasoscambioautor.setEnabled(false);
        scrollpanepasoscambioautor.setViewportView(tapasoscambioautor);

        lpasoscambioautor.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lpasoscambioautor.setText("Pasos para cambiar el autor de la canción");

        javax.swing.GroupLayout panelcambiarautorLayout = new javax.swing.GroupLayout(panelcambiarautor);
        panelcambiarautor.setLayout(panelcambiarautorLayout);
        panelcambiarautorLayout.setHorizontalGroup(
            panelcambiarautorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelcambiarautorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelcambiarautorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelcambiarautorLayout.createSequentialGroup()
                        .addComponent(lpasoscambioautor)
                        .addGap(0, 103, Short.MAX_VALUE))
                    .addComponent(scrollpanepasoscambioautor))
                .addContainerGap())
        );
        panelcambiarautorLayout.setVerticalGroup(
            panelcambiarautorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelcambiarautorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lpasoscambioautor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollpanepasoscambioautor, javax.swing.GroupLayout.DEFAULT_SIZE, 427, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelcambiarcancion.setBackground(new java.awt.Color(255, 255, 255));

        scrollpanepasoscambiocancion.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        scrollpanepasoscambiocancion.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        tapasoscambiocancion.setColumns(20);
        tapasoscambiocancion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tapasoscambiocancion.setLineWrap(true);
        tapasoscambiocancion.setRows(5);
        tapasoscambiocancion.setText("1.Seleccione la opción Opciones en el menú principal de la aplicación.\n\n2. En la casilla debajo de la etiqueta modificar nombre canción introduzca el nombre de la canción.\n\n3. Haga clic en el botón guardar.\n\n*Si una de las casillas está vacía se le notificará que no se pueden dejar los campos vacíos. \n\n**Por defecto el nombre de la canción está vacío.\n\n\n\n\n\n");
        tapasoscambiocancion.setWrapStyleWord(true);
        tapasoscambiocancion.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        tapasoscambiocancion.setEnabled(false);
        scrollpanepasoscambiocancion.setViewportView(tapasoscambiocancion);

        lpasoscambiocancion.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lpasoscambiocancion.setText("Pasos para cambiar el nombre de la canción");

        javax.swing.GroupLayout panelcambiarcancionLayout = new javax.swing.GroupLayout(panelcambiarcancion);
        panelcambiarcancion.setLayout(panelcambiarcancionLayout);
        panelcambiarcancionLayout.setHorizontalGroup(
            panelcambiarcancionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelcambiarcancionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelcambiarcancionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelcambiarcancionLayout.createSequentialGroup()
                        .addComponent(lpasoscambiocancion)
                        .addGap(0, 82, Short.MAX_VALUE))
                    .addComponent(scrollpanepasoscambiocancion))
                .addContainerGap())
        );
        panelcambiarcancionLayout.setVerticalGroup(
            panelcambiarcancionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelcambiarcancionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lpasoscambiocancion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollpanepasoscambiocancion, javax.swing.GroupLayout.DEFAULT_SIZE, 427, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelporcapasayuda.setLayer(panelhojanueva, javax.swing.JLayeredPane.DEFAULT_LAYER);
        panelporcapasayuda.setLayer(paneltransportarhoja, javax.swing.JLayeredPane.DEFAULT_LAYER);
        panelporcapasayuda.setLayer(paneleditarhoja, javax.swing.JLayeredPane.DEFAULT_LAYER);
        panelporcapasayuda.setLayer(paneleliminarhoja, javax.swing.JLayeredPane.DEFAULT_LAYER);
        panelporcapasayuda.setLayer(panelcambiarautor, javax.swing.JLayeredPane.DEFAULT_LAYER);
        panelporcapasayuda.setLayer(panelcambiarcancion, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout panelporcapasayudaLayout = new javax.swing.GroupLayout(panelporcapasayuda);
        panelporcapasayuda.setLayout(panelporcapasayudaLayout);
        panelporcapasayudaLayout.setHorizontalGroup(
            panelporcapasayudaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelhojanueva, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelporcapasayudaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(paneltransportarhoja, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panelporcapasayudaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(paneleditarhoja, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panelporcapasayudaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(paneleliminarhoja, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panelporcapasayudaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panelcambiarautor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panelporcapasayudaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panelcambiarcancion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelporcapasayudaLayout.setVerticalGroup(
            panelporcapasayudaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelhojanueva, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelporcapasayudaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(paneltransportarhoja, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panelporcapasayudaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(paneleditarhoja, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panelporcapasayudaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(paneleliminarhoja, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panelporcapasayudaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panelcambiarautor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panelporcapasayudaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panelcambiarcancion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelBarraIzq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelporcapasayuda))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBarraIzq, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelporcapasayuda)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void panelSalirmenuMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelSalirmenuMousePressed
        InicioFrame frameinicio= new InicioFrame(music);
        frameinicio.setVisible(true);
        this.setVisible(false);	       // TODO add your handling code here:
    }//GEN-LAST:event_panelSalirmenuMousePressed

    private void panelSalirmenuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelSalirmenuMouseEntered
        panelSalirmenu.setBackground(new  java.awt.Color(216,216,216));// TODO add your handling code here:
    }//GEN-LAST:event_panelSalirmenuMouseEntered

    private void panelSalirmenuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelSalirmenuMouseExited
        panelSalirmenu.setBackground(new  java.awt.Color(204,204,204));// TODO add your handling code here:
    }//GEN-LAST:event_panelSalirmenuMouseExited

    private void panelcrearhojamenuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelcrearhojamenuMouseEntered
        panelcrearhojamenu.setBackground(new  java.awt.Color(0,82,0));
    }//GEN-LAST:event_panelcrearhojamenuMouseEntered

    private void panelcrearhojamenuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelcrearhojamenuMouseExited
        panelcrearhojamenu.setBackground(new  java.awt.Color(0,102,0));
    }//GEN-LAST:event_panelcrearhojamenuMouseExited

    private void paneltransportarmenuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_paneltransportarmenuMouseEntered
        paneltransportarmenu.setBackground(new  java.awt.Color(0,82,0));
    }//GEN-LAST:event_paneltransportarmenuMouseEntered

    private void paneltransportarmenuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_paneltransportarmenuMouseExited
        paneltransportarmenu.setBackground(new  java.awt.Color(0,102,0));
    }//GEN-LAST:event_paneltransportarmenuMouseExited

    private void paneleditarmenuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_paneleditarmenuMouseEntered
        paneleditarmenu.setBackground(new  java.awt.Color(0,82,0));
    }//GEN-LAST:event_paneleditarmenuMouseEntered

    private void paneleditarmenuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_paneleditarmenuMouseExited
        paneleditarmenu.setBackground(new  java.awt.Color(0,102,0));
    }//GEN-LAST:event_paneleditarmenuMouseExited

    private void paneleliminarmenuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_paneleliminarmenuMouseEntered
        paneleliminarmenu.setBackground(new  java.awt.Color(0,82,0));
    }//GEN-LAST:event_paneleliminarmenuMouseEntered

    private void paneleliminarmenuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_paneleliminarmenuMouseExited
        paneleliminarmenu.setBackground(new  java.awt.Color(0,102,0));
    }//GEN-LAST:event_paneleliminarmenuMouseExited

    private void panelcambioautormenuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelcambioautormenuMouseEntered
        panelcambioautormenu.setBackground(new  java.awt.Color(0,82,0));
    }//GEN-LAST:event_panelcambioautormenuMouseEntered

    private void panelcambioautormenuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelcambioautormenuMouseExited
        panelcambioautormenu.setBackground(new  java.awt.Color(0,102,0));
    }//GEN-LAST:event_panelcambioautormenuMouseExited

    private void panelcambiocancionmenuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelcambiocancionmenuMouseEntered
        panelcambiocancionmenu.setBackground(new  java.awt.Color(0,82,0));
    }//GEN-LAST:event_panelcambiocancionmenuMouseEntered

    private void panelcambiocancionmenuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelcambiocancionmenuMouseExited
        panelcambiocancionmenu.setBackground(new  java.awt.Color(0,102,0));
    }//GEN-LAST:event_panelcambiocancionmenuMouseExited

    private void panelcrearhojamenuMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelcrearhojamenuMousePressed
        panelhojanueva.setVisible(true);
        paneltransportarhoja.setVisible(false);
        paneleditarhoja.setVisible(false);
        paneleliminarhoja.setVisible(false);
        panelcambiarautor.setVisible(false);
        panelcambiarcancion.setVisible(false);
    }//GEN-LAST:event_panelcrearhojamenuMousePressed

    private void paneltransportarmenuMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_paneltransportarmenuMousePressed
        panelhojanueva.setVisible(false);
        paneltransportarhoja.setVisible(true);
        paneleditarhoja.setVisible(false);
        paneleliminarhoja.setVisible(false);
        panelcambiarautor.setVisible(false);
        panelcambiarcancion.setVisible(false);
    }//GEN-LAST:event_paneltransportarmenuMousePressed

    private void paneleditarmenuMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_paneleditarmenuMousePressed
        panelhojanueva.setVisible(false);
        paneltransportarhoja.setVisible(false);
        paneleditarhoja.setVisible(true);
        paneleliminarhoja.setVisible(false);
        panelcambiarautor.setVisible(false);
        panelcambiarcancion.setVisible(false);
    }//GEN-LAST:event_paneleditarmenuMousePressed

    private void paneleliminarmenuMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_paneleliminarmenuMousePressed
        panelhojanueva.setVisible(false);
        paneltransportarhoja.setVisible(false);
        paneleditarhoja.setVisible(false);
        paneleliminarhoja.setVisible(true);
        panelcambiarautor.setVisible(false);
        panelcambiarcancion.setVisible(false);
    }//GEN-LAST:event_paneleliminarmenuMousePressed

    private void panelcambioautormenuMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelcambioautormenuMousePressed
        panelhojanueva.setVisible(false);
        paneltransportarhoja.setVisible(false);
        paneleditarhoja.setVisible(false);
        paneleliminarhoja.setVisible(false);
        panelcambiarautor.setVisible(true);
        panelcambiarcancion.setVisible(false);
    }//GEN-LAST:event_panelcambioautormenuMousePressed

    private void panelcambiocancionmenuMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelcambiocancionmenuMousePressed
        panelhojanueva.setVisible(false);
        paneltransportarhoja.setVisible(false);
        paneleditarhoja.setVisible(false);
        paneleliminarhoja.setVisible(false);
        panelcambiarautor.setVisible(false);
        panelcambiarcancion.setVisible(true);
    }//GEN-LAST:event_panelcambiocancionmenuMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AyudaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AyudaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AyudaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AyudaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AyudaFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lCambiarelautor;
    private javax.swing.JLabel lCambiarnomcancion;
    private javax.swing.JLabel lCrearhoja;
    private javax.swing.JLabel lEditarhoja;
    private javax.swing.JLabel lEliminarhoja;
    private javax.swing.JLabel lOpciones;
    private javax.swing.JLabel lPasoscrear;
    private javax.swing.JLabel lSalir;
    private javax.swing.JLabel lTransportarhoja;
    private javax.swing.JLabel lpasoscambioautor;
    private javax.swing.JLabel lpasoscambiocancion;
    private javax.swing.JLabel lpasoseditar;
    private javax.swing.JLabel lpasoseliminar;
    private javax.swing.JLabel lpasostransportar;
    private javax.swing.JPanel panelBarraIzq;
    public javax.swing.JPanel panelSalirmenu;
    private javax.swing.JPanel panelcambiarautor;
    private javax.swing.JPanel panelcambiarcancion;
    private javax.swing.JPanel panelcambioautormenu;
    private javax.swing.JPanel panelcambiocancionmenu;
    private javax.swing.JPanel panelcrearhojamenu;
    private javax.swing.JPanel paneleditarhoja;
    private javax.swing.JPanel paneleditarmenu;
    private javax.swing.JPanel paneleliminarhoja;
    private javax.swing.JPanel paneleliminarmenu;
    private javax.swing.JPanel panelhojanueva;
    private javax.swing.JLayeredPane panelporcapasayuda;
    private javax.swing.JPanel paneltransportarhoja;
    private javax.swing.JPanel paneltransportarmenu;
    private javax.swing.JScrollPane scrollpanepasoscambioautor;
    private javax.swing.JScrollPane scrollpanepasoscambiocancion;
    private javax.swing.JScrollPane scrollpanepasoscrear;
    private javax.swing.JScrollPane scrollpanepasoseditar;
    private javax.swing.JScrollPane scrollpanepasoseliminar;
    private javax.swing.JScrollPane scrollpanepasostransportar;
    private javax.swing.JTextArea tapasoscambioautor;
    private javax.swing.JTextArea tapasoscambiocancion;
    private javax.swing.JTextArea tapasoscrear;
    private javax.swing.JTextArea tapasoseditar;
    private javax.swing.JTextArea tapasoseliminar;
    private javax.swing.JTextArea tapasostransportar;
    // End of variables declaration//GEN-END:variables
}
