/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tonito;

import javax.swing.ImageIcon;



/**
 *
 * @author Federico Teixeira G
 */
public class EditarFrame extends javax.swing.JFrame {
    private HojaMusical music;
    private int posicion;
    /**
     * Creates new form NuevaHojaFrame
     */
    public EditarFrame(HojaMusical cancion,int po) {
        posicion=po;
        music=cancion;
        initComponents();
        setTitle("TonUDO");
        setIconImage(new ImageIcon(getClass().getResource("TonUDOiconoblack-01.png")).getImage());
        setLocationRelativeTo(null);
        setResizable(false);
    }
    public EditarFrame() {
        initComponents();
        setTitle("TonUDO");
        setIconImage(new ImageIcon(getClass().getResource("TonUDOiconoblack-01.png")).getImage());
        setLocationRelativeTo(null);
        setResizable(false);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBarraDer = new javax.swing.JPanel();
        panelBotones = new javax.swing.JPanel();
        panelGuardar = new javax.swing.JPanel();
        lGuardar = new javax.swing.JLabel();
        panelCancelar = new javax.swing.JPanel();
        lCancelar = new javax.swing.JLabel();
        panelNombretono = new javax.swing.JPanel();
        lNombre = new javax.swing.JLabel();
        tfNombre = new javax.swing.JTextField();
        lTonoActual = new javax.swing.JLabel();
        comboTonoActual = new javax.swing.JComboBox<>();
        lAsteriscoNombre = new javax.swing.JLabel();
        lAsteriscoCamposVacios = new javax.swing.JLabel();
        lCamposVacios = new javax.swing.JLabel();
        panelBarraIzq = new javax.swing.JPanel();
        lAcordes = new javax.swing.JLabel();
        scrollpaneAcordes = new javax.swing.JScrollPane();
        taAcordes = new javax.swing.JTextArea();
        lEditarHoja = new javax.swing.JLabel();
        lAsteriscoAcordes = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelBarraDer.setBackground(new java.awt.Color(255, 255, 255));

        panelBotones.setBackground(new java.awt.Color(255, 255, 255));

        panelGuardar.setBackground(new java.awt.Color(204, 204, 204));
        panelGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelGuardarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelGuardarMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelGuardarMousePressed(evt);
            }
        });

        lGuardar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lGuardar.setForeground(new java.awt.Color(0, 0, 0));
        lGuardar.setText("Guardar");

        javax.swing.GroupLayout panelGuardarLayout = new javax.swing.GroupLayout(panelGuardar);
        panelGuardar.setLayout(panelGuardarLayout);
        panelGuardarLayout.setHorizontalGroup(
            panelGuardarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelGuardarLayout.createSequentialGroup()
                .addContainerGap(41, Short.MAX_VALUE)
                .addComponent(lGuardar)
                .addGap(34, 34, 34))
        );
        panelGuardarLayout.setVerticalGroup(
            panelGuardarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGuardarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lGuardar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelCancelar.setBackground(new java.awt.Color(204, 204, 204));
        panelCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelCancelarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelCancelarMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelCancelarMousePressed(evt);
            }
        });

        lCancelar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lCancelar.setForeground(new java.awt.Color(0, 0, 0));
        lCancelar.setText("Cancelar");

        javax.swing.GroupLayout panelCancelarLayout = new javax.swing.GroupLayout(panelCancelar);
        panelCancelar.setLayout(panelCancelarLayout);
        panelCancelarLayout.setHorizontalGroup(
            panelCancelarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCancelarLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(lCancelar)
                .addContainerGap(32, Short.MAX_VALUE))
        );
        panelCancelarLayout.setVerticalGroup(
            panelCancelarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCancelarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lCancelar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelBotonesLayout = new javax.swing.GroupLayout(panelBotones);
        panelBotones.setLayout(panelBotonesLayout);
        panelBotonesLayout.setHorizontalGroup(
            panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBotonesLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(panelGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        panelBotonesLayout.setVerticalGroup(
            panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBotonesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelGuardar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelCancelar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelNombretono.setBackground(new java.awt.Color(255, 255, 255));

        lNombre.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        lNombre.setText("Nombre");

        tfNombre.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tfNombre.setText(music.getNombrehoja(posicion));
        tfNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfNombreKeyTyped(evt);
            }
        });

        lTonoActual.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        lTonoActual.setText("Tono actual");

        comboTonoActual.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        comboTonoActual.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cb", "C", "C#", "Db", "D", "Eb", "E", "F", "F#", "Gb", "G", "Ab", "A", "Bb", "B" }));
        comboTonoActual.setSelectedIndex(music.numeracion(music.getTonoActualhoja(posicion))/7);

        lAsteriscoNombre.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lAsteriscoNombre.setForeground(new java.awt.Color(255, 0, 0));
        lAsteriscoNombre.setText("*");
        lAsteriscoNombre.setVisible(false);

        javax.swing.GroupLayout panelNombretonoLayout = new javax.swing.GroupLayout(panelNombretono);
        panelNombretono.setLayout(panelNombretonoLayout);
        panelNombretonoLayout.setHorizontalGroup(
            panelNombretonoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNombretonoLayout.createSequentialGroup()
                .addGroup(panelNombretonoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelNombretonoLayout.createSequentialGroup()
                        .addComponent(lTonoActual)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(panelNombretonoLayout.createSequentialGroup()
                        .addComponent(lNombre)
                        .addGap(36, 36, 36)))
                .addGroup(panelNombretonoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelNombretonoLayout.createSequentialGroup()
                        .addComponent(tfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lAsteriscoNombre))
                    .addComponent(comboTonoActual, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panelNombretonoLayout.setVerticalGroup(
            panelNombretonoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNombretonoLayout.createSequentialGroup()
                .addGroup(panelNombretonoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lNombre)
                    .addComponent(tfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lAsteriscoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(panelNombretonoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lTonoActual)
                    .addComponent(comboTonoActual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 74, Short.MAX_VALUE))
        );

        lAsteriscoCamposVacios.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lAsteriscoCamposVacios.setForeground(new java.awt.Color(255, 0, 0));
        lAsteriscoCamposVacios.setText("*");
        lAsteriscoCamposVacios.setVisible(false);

        lCamposVacios.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lCamposVacios.setForeground(new java.awt.Color(255, 0, 0));
        lCamposVacios.setText("Estos campos no pueden estar vacíos");
        lCamposVacios.setVisible(false);

        javax.swing.GroupLayout panelBarraDerLayout = new javax.swing.GroupLayout(panelBarraDer);
        panelBarraDer.setLayout(panelBarraDerLayout);
        panelBarraDerLayout.setHorizontalGroup(
            panelBarraDerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBarraDerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelBarraDerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelNombretono, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelBotones, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelBarraDerLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lAsteriscoCamposVacios)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lCamposVacios)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelBarraDerLayout.setVerticalGroup(
            panelBarraDerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBarraDerLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(panelNombretono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelBarraDerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lAsteriscoCamposVacios, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lCamposVacios))
                .addGap(18, 18, 18)
                .addComponent(panelBotones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );

        panelBarraIzq.setBackground(new java.awt.Color(102, 0, 102));

        lAcordes.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        lAcordes.setForeground(new java.awt.Color(255, 255, 255));
        lAcordes.setText("Acordes");

        scrollpaneAcordes.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        scrollpaneAcordes.setAutoscrolls(true);

        taAcordes.setColumns(20);
        taAcordes.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        taAcordes.setLineWrap(true);
        taAcordes.setRows(5);
        taAcordes.setText(music.getAcordeshoja(posicion));
        taAcordes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                taAcordesKeyTyped(evt);
            }
        });
        scrollpaneAcordes.setViewportView(taAcordes);

        lEditarHoja.setFont(new java.awt.Font("Segoe UI Light", 0, 36)); // NOI18N
        lEditarHoja.setForeground(new java.awt.Color(255, 255, 255));
        lEditarHoja.setText("Editar hoja");

        lAsteriscoAcordes.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lAsteriscoAcordes.setForeground(new java.awt.Color(255, 0, 0));
        lAsteriscoAcordes.setText("*");
        lAsteriscoAcordes.setVisible(false);

        javax.swing.GroupLayout panelBarraIzqLayout = new javax.swing.GroupLayout(panelBarraIzq);
        panelBarraIzq.setLayout(panelBarraIzqLayout);
        panelBarraIzqLayout.setHorizontalGroup(
            panelBarraIzqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBarraIzqLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(panelBarraIzqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(scrollpaneAcordes, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBarraIzqLayout.createSequentialGroup()
                        .addComponent(lEditarHoja)
                        .addGap(132, 132, 132))
                    .addGroup(panelBarraIzqLayout.createSequentialGroup()
                        .addComponent(lAcordes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lAsteriscoAcordes)))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        panelBarraIzqLayout.setVerticalGroup(
            panelBarraIzqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBarraIzqLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lEditarHoja)
                .addGap(1, 1, 1)
                .addGroup(panelBarraIzqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lAcordes)
                    .addComponent(lAsteriscoAcordes, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(scrollpaneAcordes, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelBarraIzq, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelBarraDer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBarraDer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelBarraIzq, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void panelGuardarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelGuardarMousePressed
        music.editarhoja(posicion, tfNombre.getText(), comboTonoActual.getSelectedItem().toString(), taAcordes.getText());
        VerHojasFrame frameverhojas= new VerHojasFrame(music);
        frameverhojas.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_panelGuardarMousePressed

    private void panelCancelarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelCancelarMousePressed
        VerHojasFrame frameverhojas= new VerHojasFrame(music);
        frameverhojas.setVisible(true);
        this.setVisible(false);// TODO add your handling code here:
    }//GEN-LAST:event_panelCancelarMousePressed

    private void panelGuardarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelGuardarMouseEntered
        panelGuardar.setBackground(new  java.awt.Color(216,216,216));// TODO add your handling code here:
    }//GEN-LAST:event_panelGuardarMouseEntered

    private void panelGuardarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelGuardarMouseExited
        panelGuardar.setBackground(new  java.awt.Color(204,204,204));// TODO add your handling code here:
    }//GEN-LAST:event_panelGuardarMouseExited

    private void taAcordesKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_taAcordesKeyTyped
        //se agrega funcion que obliga las letras en el textbox a ser mayusculas 
         char c=evt.getKeyChar();
         //"e" es el nombre asignado al evento de tecla "c" representa a las letras
        if (Character.isLowerCase(c)){
        String cad=(""+c).toUpperCase();
        c=cad.charAt(0);
        evt.setKeyChar(c);
        }
    }//GEN-LAST:event_taAcordesKeyTyped

    private void tfNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfNombreKeyTyped
        if (tfNombre.getText().length()==10){ //El límite de caracteres es 10 para que no se desborde en el frame visualizar
         evt.consume(); //Elimina los caracteres que sean introducidos después del límite
        } 
    }//GEN-LAST:event_tfNombreKeyTyped

    private void panelCancelarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelCancelarMouseExited
        panelCancelar.setBackground(new  java.awt.Color(204,204,204));// TODO add your handling code here:
    }//GEN-LAST:event_panelCancelarMouseExited

    private void panelCancelarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelCancelarMouseEntered
        panelCancelar.setBackground(new  java.awt.Color(216,216,216));// TODO add your handling code here:
    }//GEN-LAST:event_panelCancelarMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditarFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditarFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditarFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditarFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditarFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JComboBox<String> comboTonoActual;
    private javax.swing.JLabel lAcordes;
    private javax.swing.JLabel lAsteriscoAcordes;
    private javax.swing.JLabel lAsteriscoCamposVacios;
    private javax.swing.JLabel lAsteriscoNombre;
    private javax.swing.JLabel lCamposVacios;
    private javax.swing.JLabel lCancelar;
    private javax.swing.JLabel lEditarHoja;
    private javax.swing.JLabel lGuardar;
    private javax.swing.JLabel lNombre;
    private javax.swing.JLabel lTonoActual;
    private javax.swing.JPanel panelBarraDer;
    private javax.swing.JPanel panelBarraIzq;
    private javax.swing.JPanel panelBotones;
    public javax.swing.JPanel panelCancelar;
    public javax.swing.JPanel panelGuardar;
    private javax.swing.JPanel panelNombretono;
    private javax.swing.JScrollPane scrollpaneAcordes;
    public javax.swing.JTextArea taAcordes;
    public javax.swing.JTextField tfNombre;
    // End of variables declaration//GEN-END:variables
}
