/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tonito;

import javax.swing.*;



/**
 *
 * @author Federico Teixeira G
 */
public class InicioFrame extends javax.swing.JFrame {

    /**
     * Creates new form InicioFrame
     */
    private HojaMusical music;

    public InicioFrame(HojaMusical cancion) {
        music = cancion;
        initComponents();
        setTitle("TonUDO");
        setIconImage(new ImageIcon(getClass().getResource("TonUDOiconoblack-01.png")).getImage());
        setLocationRelativeTo(null);
        setResizable(false);
    }
    public InicioFrame(){
        initComponents();
        setTitle("TonUDO");
        setIconImage(new ImageIcon(getClass().getResource("TonUDOiconoblack-01.png")).getImage());
        setLocationRelativeTo(null);
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelMenú = new javax.swing.JPanel();
        panelNuevaHoja = new javax.swing.JPanel();
        lNuevaHoja = new javax.swing.JLabel();
        panelVerHojas = new javax.swing.JPanel();
        lVerHojas = new javax.swing.JLabel();
        panelAyuda = new javax.swing.JPanel();
        lAyuda = new javax.swing.JLabel();
        panelSalir = new javax.swing.JPanel();
        lSalir = new javax.swing.JLabel();
        panelOpciones = new javax.swing.JPanel();
        lOpciones = new javax.swing.JLabel();
        panelBarraDer = new javax.swing.JPanel();
        lTonDOLogo = new javax.swing.JLabel();
        lTonudodescripcion = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        panelMenú.setBackground(new java.awt.Color(44, 62, 80));

        panelNuevaHoja.setBackground(new java.awt.Color(44, 62, 80));
        panelNuevaHoja.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelNuevaHojaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelNuevaHojaMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelNuevaHojaMousePressed(evt);
            }
        });

        lNuevaHoja.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        lNuevaHoja.setForeground(new java.awt.Color(255, 255, 255));
        lNuevaHoja.setText("Nueva hoja");

        javax.swing.GroupLayout panelNuevaHojaLayout = new javax.swing.GroupLayout(panelNuevaHoja);
        panelNuevaHoja.setLayout(panelNuevaHojaLayout);
        panelNuevaHojaLayout.setHorizontalGroup(
            panelNuevaHojaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNuevaHojaLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(lNuevaHoja)
                .addGap(151, 151, 151))
        );
        panelNuevaHojaLayout.setVerticalGroup(
            panelNuevaHojaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelNuevaHojaLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(lNuevaHoja)
                .addGap(20, 20, 20))
        );

        panelVerHojas.setBackground(new java.awt.Color(44, 62, 80));
        panelVerHojas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelVerHojasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelVerHojasMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelVerHojasMousePressed(evt);
            }
        });

        lVerHojas.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        lVerHojas.setForeground(new java.awt.Color(255, 255, 255));
        lVerHojas.setText("Ver hojas");

        javax.swing.GroupLayout panelVerHojasLayout = new javax.swing.GroupLayout(panelVerHojas);
        panelVerHojas.setLayout(panelVerHojasLayout);
        panelVerHojasLayout.setHorizontalGroup(
            panelVerHojasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelVerHojasLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(lVerHojas)
                .addGap(168, 168, 168))
        );
        panelVerHojasLayout.setVerticalGroup(
            panelVerHojasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelVerHojasLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(lVerHojas)
                .addGap(20, 20, 20))
        );

        panelAyuda.setBackground(new java.awt.Color(44, 62, 80));
        panelAyuda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelAyudaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelAyudaMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelAyudaMousePressed(evt);
            }
        });

        lAyuda.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        lAyuda.setForeground(new java.awt.Color(255, 255, 255));
        lAyuda.setText("Ayuda");

        javax.swing.GroupLayout panelAyudaLayout = new javax.swing.GroupLayout(panelAyuda);
        panelAyuda.setLayout(panelAyudaLayout);
        panelAyudaLayout.setHorizontalGroup(
            panelAyudaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAyudaLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(lAyuda)
                .addGap(197, 197, 197))
        );
        panelAyudaLayout.setVerticalGroup(
            panelAyudaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAyudaLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(lAyuda)
                .addGap(20, 20, 20))
        );

        panelSalir.setBackground(new java.awt.Color(44, 62, 80));
        panelSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelSalirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelSalirMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelSalirMousePressed(evt);
            }
        });

        lSalir.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        lSalir.setForeground(new java.awt.Color(255, 255, 255));
        lSalir.setText("Salir");

        javax.swing.GroupLayout panelSalirLayout = new javax.swing.GroupLayout(panelSalir);
        panelSalir.setLayout(panelSalirLayout);
        panelSalirLayout.setHorizontalGroup(
            panelSalirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSalirLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(lSalir)
                .addGap(219, 219, 219))
        );
        panelSalirLayout.setVerticalGroup(
            panelSalirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSalirLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(lSalir)
                .addGap(20, 20, 20))
        );

        panelOpciones.setBackground(new java.awt.Color(44, 62, 80));
        panelOpciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelOpcionesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelOpcionesMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelOpcionesMousePressed(evt);
            }
        });

        lOpciones.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        lOpciones.setForeground(new java.awt.Color(255, 255, 255));
        lOpciones.setText("Opciones");

        javax.swing.GroupLayout panelOpcionesLayout = new javax.swing.GroupLayout(panelOpciones);
        panelOpciones.setLayout(panelOpcionesLayout);
        panelOpcionesLayout.setHorizontalGroup(
            panelOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOpcionesLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(lOpciones)
                .addGap(168, 168, 168))
        );
        panelOpcionesLayout.setVerticalGroup(
            panelOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOpcionesLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(lOpciones)
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout panelMenúLayout = new javax.swing.GroupLayout(panelMenú);
        panelMenú.setLayout(panelMenúLayout);
        panelMenúLayout.setHorizontalGroup(
            panelMenúLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelNuevaHoja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(panelVerHojas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelAyuda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelOpciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelMenúLayout.setVerticalGroup(
            panelMenúLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenúLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(panelNuevaHoja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(panelVerHojas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(panelAyuda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(panelOpciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(panelSalir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelBarraDer.setBackground(new java.awt.Color(255, 255, 255));

        lTonDOLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tonito/TonUDOcolors-01.png"))); // NOI18N

        lTonudodescripcion.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        lTonudodescripcion.setText("TonUDO Transportador de acordes");

        javax.swing.GroupLayout panelBarraDerLayout = new javax.swing.GroupLayout(panelBarraDer);
        panelBarraDer.setLayout(panelBarraDerLayout);
        panelBarraDerLayout.setHorizontalGroup(
            panelBarraDerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBarraDerLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(panelBarraDerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lTonudodescripcion)
                    .addGroup(panelBarraDerLayout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(lTonDOLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30))
        );
        panelBarraDerLayout.setVerticalGroup(
            panelBarraDerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBarraDerLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(lTonDOLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lTonudodescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(111, 111, 111))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelMenú, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelBarraDer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBarraDer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelMenú, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void panelOpcionesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelOpcionesMousePressed
        OpcionesFrame frameopciones= new OpcionesFrame(music);
        frameopciones.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_panelOpcionesMousePressed

    private void panelOpcionesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelOpcionesMouseEntered
        panelOpciones.setBackground(new java.awt.Color(51, 81, 115));// TODO add your handling code here:
    }//GEN-LAST:event_panelOpcionesMouseEntered

    private void panelSalirMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelSalirMousePressed
        System.exit(0);// TODO add your handling code here:
    }//GEN-LAST:event_panelSalirMousePressed

    private void panelSalirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelSalirMouseExited
        panelSalir.setBackground(new java.awt.Color(44, 62, 80));// TODO add your handling code here:
    }//GEN-LAST:event_panelSalirMouseExited

    private void panelSalirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelSalirMouseEntered
        panelSalir.setBackground(new java.awt.Color(51, 81, 115));// TODO add your handling code here:
    }//GEN-LAST:event_panelSalirMouseEntered

    private void panelAyudaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelAyudaMouseExited
        panelAyuda.setBackground(new java.awt.Color(44, 62, 80));// TODO add your handling code here:
    }//GEN-LAST:event_panelAyudaMouseExited

    private void panelAyudaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelAyudaMouseEntered
        panelAyuda.setBackground(new java.awt.Color(51, 81, 115));// TODO add your handling code here:
    }//GEN-LAST:event_panelAyudaMouseEntered

    private void panelVerHojasMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelVerHojasMousePressed
        VerHojasFrame frameverhojas= new VerHojasFrame(music);
        frameverhojas.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_panelVerHojasMousePressed

    private void panelVerHojasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelVerHojasMouseExited
        panelVerHojas.setBackground(new java.awt.Color(44, 62, 80));// TODO add your handling code here:
    }//GEN-LAST:event_panelVerHojasMouseExited

    private void panelVerHojasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelVerHojasMouseEntered
        panelVerHojas.setBackground(new java.awt.Color(51, 81, 115));// TODO add your handling code here:
    }//GEN-LAST:event_panelVerHojasMouseEntered

    private void panelNuevaHojaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelNuevaHojaMousePressed
        NuevaHojaFrame framenuevahoja= new NuevaHojaFrame(music);
        framenuevahoja.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_panelNuevaHojaMousePressed

    private void panelNuevaHojaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelNuevaHojaMouseExited
        panelNuevaHoja.setBackground(new java.awt.Color(44, 62, 80));// TODO add your handling code here:
    }//GEN-LAST:event_panelNuevaHojaMouseExited

    private void panelNuevaHojaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelNuevaHojaMouseEntered
        panelNuevaHoja.setBackground(new java.awt.Color(51, 81, 115));// TODO add your handling code here:
        
    }//GEN-LAST:event_panelNuevaHojaMouseEntered

    private void panelOpcionesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelOpcionesMouseExited
        panelOpciones.setBackground(new java.awt.Color(44, 62, 80));// TODO add your handling code here:
    }//GEN-LAST:event_panelOpcionesMouseExited

    private void panelAyudaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelAyudaMousePressed
        AyudaFrame frameayuda= new AyudaFrame(music);
        frameayuda.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_panelAyudaMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InicioFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InicioFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InicioFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InicioFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InicioFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lAyuda;
    private javax.swing.JLabel lNuevaHoja;
    private javax.swing.JLabel lOpciones;
    private javax.swing.JLabel lSalir;
    private javax.swing.JLabel lTonDOLogo;
    private javax.swing.JLabel lTonudodescripcion;
    private javax.swing.JLabel lVerHojas;
    public javax.swing.JPanel panelAyuda;
    private javax.swing.JPanel panelBarraDer;
    private javax.swing.JPanel panelMenú;
    public javax.swing.JPanel panelNuevaHoja;
    public javax.swing.JPanel panelOpciones;
    public javax.swing.JPanel panelSalir;
    public javax.swing.JPanel panelVerHojas;
    // End of variables declaration//GEN-END:variables
}
