/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tonito;

import javax.swing.ImageIcon;



/**
 *
 * @author Federico Teixeira G
 */
public class OpcionesFrame extends javax.swing.JFrame {
    private HojaMusical music;
    /**
     * Creates new form OpcionesFrame
     */
    public OpcionesFrame() {
        initComponents();
        setTitle("TonUDO");
        setIconImage(new ImageIcon(getClass().getResource("TonUDOiconoblack-01.png")).getImage());
        setLocationRelativeTo(null);
        setResizable(false);
    }
    public OpcionesFrame(HojaMusical cancion) {
        music=cancion;
        initComponents();
        setTitle("TonUDO");
        setIconImage(new ImageIcon(getClass().getResource("TonUDOiconoblack-01.png")).getImage());
        setLocationRelativeTo(null);
        setResizable(false);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBarraIzq = new javax.swing.JPanel();
        panelOpcautnom = new javax.swing.JPanel();
        lModifAutor = new javax.swing.JLabel();
        paneltfNomcan = new javax.swing.JPanel();
        tfNombreCancion = new javax.swing.JTextField();
        lAsteriscoModificarNombreCancion = new javax.swing.JLabel();
        panelNomaut = new javax.swing.JPanel();
        tfAutor = new javax.swing.JTextField();
        lAsteriscoModificarAutor = new javax.swing.JLabel();
        lModifNombreCancion = new javax.swing.JLabel();
        lOpciones = new javax.swing.JLabel();
        panelbotonguar = new javax.swing.JPanel();
        panelGuardar = new javax.swing.JPanel();
        lGuardar = new javax.swing.JLabel();
        lCamposVacios = new javax.swing.JLabel();
        panelBarraDer = new javax.swing.JPanel();
        lTonUDO = new javax.swing.JLabel();
        lCopyright = new javax.swing.JLabel();
        lVersion = new javax.swing.JLabel();
        panelSalir = new javax.swing.JPanel();
        lSalir = new javax.swing.JLabel();
        lDescripcion = new javax.swing.JLabel();
        lUDOAnz = new javax.swing.JLabel();
        lTonoUDOlogo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelBarraIzq.setBackground(new java.awt.Color(102, 0, 0));

        panelOpcautnom.setBackground(new java.awt.Color(102, 0, 0));

        lModifAutor.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        lModifAutor.setForeground(new java.awt.Color(255, 255, 255));
        lModifAutor.setText("Modificar autor");

        paneltfNomcan.setBackground(new java.awt.Color(102, 0, 0));

        tfNombreCancion.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tfNombreCancion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfNombreCancionKeyTyped(evt);
            }
        });

        lAsteriscoModificarNombreCancion.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lAsteriscoModificarNombreCancion.setForeground(new java.awt.Color(255, 0, 0));
        lAsteriscoModificarNombreCancion.setText("*");
        lAsteriscoModificarNombreCancion.setVisible(false);

        javax.swing.GroupLayout paneltfNomcanLayout = new javax.swing.GroupLayout(paneltfNomcan);
        paneltfNomcan.setLayout(paneltfNomcanLayout);
        paneltfNomcanLayout.setHorizontalGroup(
            paneltfNomcanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneltfNomcanLayout.createSequentialGroup()
                .addComponent(tfNombreCancion, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(lAsteriscoModificarNombreCancion)
                .addContainerGap(40, Short.MAX_VALUE))
        );
        paneltfNomcanLayout.setVerticalGroup(
            paneltfNomcanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tfNombreCancion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(lAsteriscoModificarNombreCancion, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        panelNomaut.setBackground(new java.awt.Color(102, 0, 0));

        tfAutor.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tfAutor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfAutorKeyTyped(evt);
            }
        });

        lAsteriscoModificarAutor.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lAsteriscoModificarAutor.setForeground(new java.awt.Color(255, 0, 0));
        lAsteriscoModificarAutor.setText("*");
        lAsteriscoModificarAutor.setVisible(false);

        javax.swing.GroupLayout panelNomautLayout = new javax.swing.GroupLayout(panelNomaut);
        panelNomaut.setLayout(panelNomautLayout);
        panelNomautLayout.setHorizontalGroup(
            panelNomautLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNomautLayout.createSequentialGroup()
                .addComponent(tfAutor, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(lAsteriscoModificarAutor)
                .addGap(0, 0, 0))
        );
        panelNomautLayout.setVerticalGroup(
            panelNomautLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tfAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(lAsteriscoModificarAutor, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        lModifNombreCancion.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        lModifNombreCancion.setForeground(new java.awt.Color(255, 255, 255));
        lModifNombreCancion.setText("Modificar nombre canción");

        lOpciones.setFont(new java.awt.Font("Segoe UI Light", 0, 36)); // NOI18N
        lOpciones.setForeground(new java.awt.Color(255, 255, 255));
        lOpciones.setText("Opciones");

        javax.swing.GroupLayout panelOpcautnomLayout = new javax.swing.GroupLayout(panelOpcautnom);
        panelOpcautnom.setLayout(panelOpcautnomLayout);
        panelOpcautnomLayout.setHorizontalGroup(
            panelOpcautnomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelNomaut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelOpcautnomLayout.createSequentialGroup()
                .addGroup(panelOpcautnomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lModifNombreCancion)
                    .addComponent(lOpciones)
                    .addComponent(lModifAutor))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panelOpcautnomLayout.createSequentialGroup()
                .addComponent(paneltfNomcan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panelOpcautnomLayout.setVerticalGroup(
            panelOpcautnomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelOpcautnomLayout.createSequentialGroup()
                .addComponent(lOpciones)
                .addGap(0, 0, 0)
                .addComponent(lModifAutor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(panelNomaut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lModifNombreCancion)
                .addGap(11, 11, 11)
                .addComponent(paneltfNomcan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        panelbotonguar.setBackground(new java.awt.Color(102, 0, 0));

        panelGuardar.setBackground(new java.awt.Color(204, 204, 204));
        panelGuardar.setPreferredSize(new java.awt.Dimension(133, 47));
        panelGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelGuardarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelGuardarMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelGuardarMousePressed(evt);
            }
        });

        lGuardar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lGuardar.setForeground(new java.awt.Color(0, 0, 0));
        lGuardar.setText("Guardar");

        javax.swing.GroupLayout panelGuardarLayout = new javax.swing.GroupLayout(panelGuardar);
        panelGuardar.setLayout(panelGuardarLayout);
        panelGuardarLayout.setHorizontalGroup(
            panelGuardarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelGuardarLayout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addComponent(lGuardar)
                .addGap(33, 33, 33))
        );
        panelGuardarLayout.setVerticalGroup(
            panelGuardarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGuardarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lGuardar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelbotonguarLayout = new javax.swing.GroupLayout(panelbotonguar);
        panelbotonguar.setLayout(panelbotonguarLayout);
        panelbotonguarLayout.setHorizontalGroup(
            panelbotonguarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelbotonguarLayout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addComponent(panelGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(91, 91, 91))
        );
        panelbotonguarLayout.setVerticalGroup(
            panelbotonguarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelbotonguarLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(panelGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        lCamposVacios.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lCamposVacios.setForeground(new java.awt.Color(102, 0, 0));
        lCamposVacios.setText("*Estos campos no pueden estar vacíos");

        javax.swing.GroupLayout panelBarraIzqLayout = new javax.swing.GroupLayout(panelBarraIzq);
        panelBarraIzq.setLayout(panelBarraIzqLayout);
        panelBarraIzqLayout.setHorizontalGroup(
            panelBarraIzqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBarraIzqLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(lCamposVacios)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panelBarraIzqLayout.createSequentialGroup()
                .addGroup(panelBarraIzqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelBarraIzqLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(panelOpcautnom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(panelbotonguar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelBarraIzqLayout.setVerticalGroup(
            panelBarraIzqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBarraIzqLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelOpcautnom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(118, 118, 118)
                .addComponent(lCamposVacios)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelbotonguar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );

        panelBarraDer.setBackground(new java.awt.Color(255, 255, 255));

        lTonUDO.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lTonUDO.setText("TonUDO");

        lCopyright.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lCopyright.setText("Copyright ©2018 Federico Teixeira Garrido & Fadel Prado");

        lVersion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lVersion.setText("Versión 0.00.1");

        panelSalir.setBackground(new java.awt.Color(204, 204, 204));
        panelSalir.setPreferredSize(new java.awt.Dimension(133, 47));
        panelSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelSalirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelSalirMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelSalirMousePressed(evt);
            }
        });

        lSalir.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lSalir.setForeground(new java.awt.Color(0, 0, 0));
        lSalir.setText("Salir");

        javax.swing.GroupLayout panelSalirLayout = new javax.swing.GroupLayout(panelSalir);
        panelSalir.setLayout(panelSalirLayout);
        panelSalirLayout.setHorizontalGroup(
            panelSalirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSalirLayout.createSequentialGroup()
                .addContainerGap(51, Short.MAX_VALUE)
                .addComponent(lSalir)
                .addGap(49, 49, 49))
        );
        panelSalirLayout.setVerticalGroup(
            panelSalirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSalirLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lSalir)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lDescripcion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lDescripcion.setText("TonUDO - Transportador de Acordes");

        lUDOAnz.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lUDOAnz.setText("Universidad De Oriente - Núcleo Anzoátegui");

        lTonoUDOlogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tonito/TonUDOcolorsmed-01.png"))); // NOI18N

        javax.swing.GroupLayout panelBarraDerLayout = new javax.swing.GroupLayout(panelBarraDer);
        panelBarraDer.setLayout(panelBarraDerLayout);
        panelBarraDerLayout.setHorizontalGroup(
            panelBarraDerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBarraDerLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(panelBarraDerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBarraDerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelBarraDerLayout.createSequentialGroup()
                            .addGap(99, 99, 99)
                            .addGroup(panelBarraDerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lTonUDO, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBarraDerLayout.createSequentialGroup()
                                    .addComponent(lVersion)
                                    .addGap(23, 23, 23)))
                            .addGap(110, 110, 110))
                        .addComponent(lCopyright, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBarraDerLayout.createSequentialGroup()
                            .addComponent(lUDOAnz)
                            .addGap(38, 38, 38))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBarraDerLayout.createSequentialGroup()
                            .addGroup(panelBarraDerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lTonoUDOlogo)
                                .addComponent(lDescripcion))
                            .addGap(62, 62, 62)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBarraDerLayout.createSequentialGroup()
                        .addComponent(panelSalir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelBarraDerLayout.setVerticalGroup(
            panelBarraDerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBarraDerLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lTonoUDOlogo)
                .addGap(11, 11, 11)
                .addComponent(lTonUDO)
                .addGap(1, 1, 1)
                .addComponent(lVersion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lDescripcion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lCopyright)
                .addGap(1, 1, 1)
                .addComponent(lUDOAnz)
                .addGap(27, 27, 27)
                .addComponent(panelSalir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelBarraIzq, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelBarraDer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBarraDer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelBarraIzq, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void panelSalirMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelSalirMousePressed
        InicioFrame frameinicio= new InicioFrame(music);
        frameinicio.setVisible(true);
        this.setVisible(false);	       // TODO add your handling code here:
    }//GEN-LAST:event_panelSalirMousePressed

    private void panelGuardarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelGuardarMouseEntered
        panelGuardar.setBackground(new  java.awt.Color(216,216,216));// TODO add your handling code here:
    }//GEN-LAST:event_panelGuardarMouseEntered

    private void panelGuardarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelGuardarMouseExited
        panelGuardar.setBackground(new  java.awt.Color(204,204,204));// TODO add your handling code here:
    }//GEN-LAST:event_panelGuardarMouseExited

    private void panelSalirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelSalirMouseEntered
        panelSalir.setBackground(new  java.awt.Color(216,216,216));// TODO add your handling code here:
    }//GEN-LAST:event_panelSalirMouseEntered

    private void panelSalirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelSalirMouseExited
        panelSalir.setBackground(new  java.awt.Color(204,204,204));// TODO add your handling code here:
    }//GEN-LAST:event_panelSalirMouseExited

    private void panelGuardarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelGuardarMousePressed
        if(tfAutor.getText().isEmpty()||tfNombreCancion.getText().isEmpty()){
            
            lAsteriscoModificarAutor.setVisible(true);
            lAsteriscoModificarNombreCancion.setVisible(true);
            lCamposVacios.setForeground(new java.awt.Color(255,0,0));
            
        }else{
            
            lAsteriscoModificarAutor.setVisible(false);
            lAsteriscoModificarNombreCancion.setVisible(false);
            lCamposVacios.setForeground(new java.awt.Color(102,0,0));
            music.setAutor(tfAutor.getText());
            music.setNombre(tfNombreCancion.getText());
            InicioFrame frameinicio= new InicioFrame(music);    
            frameinicio.setVisible(true);
            this.setVisible(false);	
        }
    }//GEN-LAST:event_panelGuardarMousePressed

    private void tfAutorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfAutorKeyTyped
        if (tfAutor.getText().length()==16){ //El límite de caracteres es 16 para que no se desborde en el frame verhoja (y para que se pueda escribir Federico y Fadel jejeje ☺)
         evt.consume(); //Elimina los caracteres que sean introducidos después del límite
        } 
    }//GEN-LAST:event_tfAutorKeyTyped

    private void tfNombreCancionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfNombreCancionKeyTyped
        if (tfNombreCancion.getText().length()==16){ //El límite de caracteres es 16 para que no se desborde en el frame verhoja
         evt.consume(); //Elimina los caracteres que sean introducidos después del límite
        } 
    }//GEN-LAST:event_tfNombreCancionKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OpcionesFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OpcionesFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OpcionesFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OpcionesFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OpcionesFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lAsteriscoModificarAutor;
    private javax.swing.JLabel lAsteriscoModificarNombreCancion;
    private javax.swing.JLabel lCamposVacios;
    private javax.swing.JLabel lCopyright;
    private javax.swing.JLabel lDescripcion;
    private javax.swing.JLabel lGuardar;
    private javax.swing.JLabel lModifAutor;
    private javax.swing.JLabel lModifNombreCancion;
    private javax.swing.JLabel lOpciones;
    private javax.swing.JLabel lSalir;
    private javax.swing.JLabel lTonUDO;
    private javax.swing.JLabel lTonoUDOlogo;
    private javax.swing.JLabel lUDOAnz;
    private javax.swing.JLabel lVersion;
    private javax.swing.JPanel panelBarraDer;
    private javax.swing.JPanel panelBarraIzq;
    public javax.swing.JPanel panelGuardar;
    private javax.swing.JPanel panelNomaut;
    private javax.swing.JPanel panelOpcautnom;
    public javax.swing.JPanel panelSalir;
    private javax.swing.JPanel panelbotonguar;
    private javax.swing.JPanel paneltfNomcan;
    public javax.swing.JTextField tfAutor;
    public javax.swing.JTextField tfNombreCancion;
    // End of variables declaration//GEN-END:variables
}
