/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tonito;

import javax.swing.ImageIcon;



/**
 *
 * @author Federico Teixeira G
 */
public class TransportarFrame extends javax.swing.JFrame {
    private HojaMusical music;
    private int posicion;
    /**
     * Creates new form NuevaHojaFrame
     */
    public TransportarFrame() {
        initComponents();
        setTitle("TonUDO");
        setIconImage(new ImageIcon(getClass().getResource("TonUDOiconoblack-01.png")).getImage());
        setLocationRelativeTo(null);
        setResizable(false);
    }
    
    public TransportarFrame(HojaMusical cancion, int po) {
        music=cancion;
        posicion=po;
        initComponents();
        setTitle("TonUDO");
        setIconImage(new ImageIcon(getClass().getResource("TonUDOiconoblack-01.png")).getImage());
        setLocationRelativeTo(null);
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBarraDer = new javax.swing.JPanel();
        PanelNombreTono = new javax.swing.JPanel();
        comboTonoNuevo = new javax.swing.JComboBox<>();
        lTonoNuevo = new javax.swing.JLabel();
        lTonoActual = new javax.swing.JLabel();
        tfTonoActual = new javax.swing.JTextField();
        lNombre = new javax.swing.JLabel();
        tfNombre = new javax.swing.JTextField();
        panelBotones = new javax.swing.JPanel();
        panelGuardar = new javax.swing.JPanel();
        lGuardar = new javax.swing.JLabel();
        panelCancelar = new javax.swing.JPanel();
        lCancelar = new javax.swing.JLabel();
        panelBarraIzq = new javax.swing.JPanel();
        lAcordes = new javax.swing.JLabel();
        scrollpaneAcordes = new javax.swing.JScrollPane();
        taAcordes = new javax.swing.JTextArea();
        lTransportarHoja = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelBarraDer.setBackground(new java.awt.Color(255, 255, 255));

        PanelNombreTono.setBackground(new java.awt.Color(255, 255, 255));

        comboTonoNuevo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        comboTonoNuevo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cb", "C", "C#", "Db", "D", "Eb", "E", "F", "F#", "Gb", "G", "Ab", "A", "Bb", "B" }));
        comboTonoNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboTonoNuevoActionPerformed(evt);
            }
        });

        lTonoNuevo.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        lTonoNuevo.setText("Tono nuevo");

        lTonoActual.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        lTonoActual.setText("Tono actual");

        tfTonoActual.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tfTonoActual.setEnabled(false);
        tfTonoActual.setText(music.getTonoActualhoja(posicion));

        lNombre.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        lNombre.setText("Nombre");

        tfNombre.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tfNombre.setEnabled(false);
        tfNombre.setText(music.getNombrehoja(posicion));

        javax.swing.GroupLayout PanelNombreTonoLayout = new javax.swing.GroupLayout(PanelNombreTono);
        PanelNombreTono.setLayout(PanelNombreTonoLayout);
        PanelNombreTonoLayout.setHorizontalGroup(
            PanelNombreTonoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelNombreTonoLayout.createSequentialGroup()
                .addGroup(PanelNombreTonoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelNombreTonoLayout.createSequentialGroup()
                        .addComponent(lNombre)
                        .addGap(36, 36, 36)
                        .addComponent(tfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelNombreTonoLayout.createSequentialGroup()
                        .addComponent(lTonoActual)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tfTonoActual, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelNombreTonoLayout.createSequentialGroup()
                        .addComponent(lTonoNuevo)
                        .addGap(8, 8, 8)
                        .addComponent(comboTonoNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30))
        );
        PanelNombreTonoLayout.setVerticalGroup(
            PanelNombreTonoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelNombreTonoLayout.createSequentialGroup()
                .addGroup(PanelNombreTonoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lNombre)
                    .addComponent(tfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelNombreTonoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfTonoActual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lTonoActual))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelNombreTonoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lTonoNuevo)
                    .addComponent(comboTonoNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29))
        );

        panelBotones.setBackground(new java.awt.Color(255, 255, 255));

        panelGuardar.setBackground(new java.awt.Color(204, 204, 204));
        panelGuardar.setForeground(new java.awt.Color(0, 0, 0));
        panelGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelGuardarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelGuardarMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelGuardarMousePressed(evt);
            }
        });

        lGuardar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lGuardar.setForeground(new java.awt.Color(0, 0, 0));
        lGuardar.setText("Guardar");

        javax.swing.GroupLayout panelGuardarLayout = new javax.swing.GroupLayout(panelGuardar);
        panelGuardar.setLayout(panelGuardarLayout);
        panelGuardarLayout.setHorizontalGroup(
            panelGuardarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelGuardarLayout.createSequentialGroup()
                .addContainerGap(41, Short.MAX_VALUE)
                .addComponent(lGuardar)
                .addGap(34, 34, 34))
        );
        panelGuardarLayout.setVerticalGroup(
            panelGuardarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGuardarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lGuardar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelCancelar.setBackground(new java.awt.Color(204, 204, 204));
        panelCancelar.setForeground(new java.awt.Color(0, 0, 0));
        panelCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelCancelarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelCancelarMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelCancelarMousePressed(evt);
            }
        });

        lCancelar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lCancelar.setForeground(new java.awt.Color(0, 0, 0));
        lCancelar.setText("Cancelar");

        javax.swing.GroupLayout panelCancelarLayout = new javax.swing.GroupLayout(panelCancelar);
        panelCancelar.setLayout(panelCancelarLayout);
        panelCancelarLayout.setHorizontalGroup(
            panelCancelarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCancelarLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(lCancelar)
                .addContainerGap(32, Short.MAX_VALUE))
        );
        panelCancelarLayout.setVerticalGroup(
            panelCancelarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCancelarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lCancelar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelBotonesLayout = new javax.swing.GroupLayout(panelBotones);
        panelBotones.setLayout(panelBotonesLayout);
        panelBotonesLayout.setHorizontalGroup(
            panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBotonesLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(panelGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelBotonesLayout.setVerticalGroup(
            panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBotonesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelGuardar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelCancelar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelBarraDerLayout = new javax.swing.GroupLayout(panelBarraDer);
        panelBarraDer.setLayout(panelBarraDerLayout);
        panelBarraDerLayout.setHorizontalGroup(
            panelBarraDerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBarraDerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelBarraDerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PanelNombreTono, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelBotones, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelBarraDerLayout.setVerticalGroup(
            panelBarraDerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBarraDerLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(PanelNombreTono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelBotones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );

        panelBarraIzq.setBackground(new java.awt.Color(102, 102, 0));

        lAcordes.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        lAcordes.setForeground(new java.awt.Color(255, 255, 255));
        lAcordes.setText("Acordes");

        scrollpaneAcordes.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        scrollpaneAcordes.setAutoscrolls(true);

        taAcordes.setColumns(20);
        taAcordes.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        taAcordes.setLineWrap(true);
        taAcordes.setRows(5);
        taAcordes.setEnabled(false);
        taAcordes.setText(music.getAcordeshoja(posicion));
        scrollpaneAcordes.setViewportView(taAcordes);

        lTransportarHoja.setFont(new java.awt.Font("Segoe UI Light", 0, 36)); // NOI18N
        lTransportarHoja.setForeground(new java.awt.Color(255, 255, 255));
        lTransportarHoja.setText("Transportar hoja");

        javax.swing.GroupLayout panelBarraIzqLayout = new javax.swing.GroupLayout(panelBarraIzq);
        panelBarraIzq.setLayout(panelBarraIzqLayout);
        panelBarraIzqLayout.setHorizontalGroup(
            panelBarraIzqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBarraIzqLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(panelBarraIzqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lAcordes)
                    .addComponent(scrollpaneAcordes, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(lTransportarHoja, javax.swing.GroupLayout.DEFAULT_SIZE, 292, Short.MAX_VALUE))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        panelBarraIzqLayout.setVerticalGroup(
            panelBarraIzqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBarraIzqLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lTransportarHoja)
                .addGap(1, 1, 1)
                .addComponent(lAcordes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(scrollpaneAcordes, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelBarraIzq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelBarraDer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBarraDer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelBarraIzq, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboTonoNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboTonoNuevoActionPerformed
        HojaMusical musicaux= new HojaMusical("","",1);
        Acordes acordaux= new Acordes(music.getAcordeshoja(posicion),music.getTonoActualhoja(posicion),music.getNombrehoja(posicion));
        musicaux.nuevahoja(acordaux);
        musicaux.transportarhoja(posicion, comboTonoNuevo.getSelectedItem().toString());
        taAcordes.setText(musicaux.getAcordeshoja(posicion));
        tfTonoActual.setText(musicaux.getTonoActualhoja(posicion));
        tfNombre.setText(musicaux.getNombrehoja(posicion));
        comboTonoNuevo.setSelectedIndex(musicaux.numeracion(comboTonoNuevo.getSelectedItem().toString())/7);
    }//GEN-LAST:event_comboTonoNuevoActionPerformed

    private void panelGuardarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelGuardarMousePressed
        music.transportarhoja(posicion, comboTonoNuevo.getSelectedItem().toString());
        taAcordes.setText(music.getAcordeshoja(posicion));
        tfTonoActual.setText(music.getTonoActualhoja(posicion));
        tfNombre.setText(music.getNombrehoja(posicion));
        comboTonoNuevo.setSelectedIndex(music.numeracion(comboTonoNuevo.getSelectedItem().toString())/7);

        VerHojasFrame frameverhojas= new VerHojasFrame(music);
        frameverhojas.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_panelGuardarMousePressed

    private void panelCancelarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelCancelarMousePressed
        
        
        VerHojasFrame frameverhojas= new VerHojasFrame(music);
        frameverhojas.setVisible(true);
        this.setVisible(false);// TODO add your handling code here:
    }//GEN-LAST:event_panelCancelarMousePressed

    private void panelGuardarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelGuardarMouseEntered
        panelGuardar.setBackground(new  java.awt.Color(216,216,216));// TODO add your handling code here:
    }//GEN-LAST:event_panelGuardarMouseEntered

    private void panelGuardarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelGuardarMouseExited
        panelGuardar.setBackground(new  java.awt.Color(204,204,204));// TODO add your handling code here:
    }//GEN-LAST:event_panelGuardarMouseExited

    private void panelCancelarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelCancelarMouseEntered
        panelCancelar.setBackground(new  java.awt.Color(216,216,216));// TODO add your handling code here:
    }//GEN-LAST:event_panelCancelarMouseEntered

    private void panelCancelarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelCancelarMouseExited
        panelCancelar.setBackground(new  java.awt.Color(204,204,204));// TODO add your handling code here:
    }//GEN-LAST:event_panelCancelarMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TransportarFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TransportarFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TransportarFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TransportarFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TransportarFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelNombreTono;
    public javax.swing.JComboBox<String> comboTonoNuevo;
    private javax.swing.JLabel lAcordes;
    private javax.swing.JLabel lCancelar;
    private javax.swing.JLabel lGuardar;
    private javax.swing.JLabel lNombre;
    private javax.swing.JLabel lTonoActual;
    private javax.swing.JLabel lTonoNuevo;
    private javax.swing.JLabel lTransportarHoja;
    private javax.swing.JPanel panelBarraDer;
    private javax.swing.JPanel panelBarraIzq;
    private javax.swing.JPanel panelBotones;
    public javax.swing.JPanel panelCancelar;
    public javax.swing.JPanel panelGuardar;
    private javax.swing.JScrollPane scrollpaneAcordes;
    public javax.swing.JTextArea taAcordes;
    public javax.swing.JTextField tfNombre;
    public javax.swing.JTextField tfTonoActual;
    // End of variables declaration//GEN-END:variables
}
