package tonito;

import javax.swing.*;
import javax.swing.DefaultListModel;
/**
 *
 * @author Federico Teixeira G
 */
public class VerHojasFrame extends javax.swing.JFrame {
    private HojaMusical music;
    private DefaultListModel modelo;
    /**
     * Creates new form VerHojasFrame
     */
    public VerHojasFrame() {
        modelo = new DefaultListModel();
        initComponents();
        listaHojas.setModel(modelo);
        setTitle("TonUDO");
        setIconImage(new ImageIcon(getClass().getResource("TonUDOiconoblack-01.png")).getImage());
        setLocationRelativeTo(null);
        setResizable(false);
    }
    public VerHojasFrame(HojaMusical cancion) {
        music=cancion;
        modelo = new DefaultListModel();
        initComponents();
        listaHojas.setModel(modelo);
        setTitle("TonUDO");
        setIconImage(new ImageIcon(getClass().getResource("TonUDOiconoblack-01.png")).getImage());
        setLocationRelativeTo(null);
        setResizable(false);  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBarraIzq = new javax.swing.JPanel();
        lVerHojas = new javax.swing.JLabel();
        panelSalir = new javax.swing.JPanel();
        lSalir = new javax.swing.JLabel();
        panelBarraDer = new javax.swing.JPanel();
        lCancion = new javax.swing.JLabel();
        lAutor = new javax.swing.JLabel();
        scrollpaneListaHojas = new javax.swing.JScrollPane();
        listaHojas = new javax.swing.JList<>();
        panelTransportar = new javax.swing.JPanel();
        lTransportar = new javax.swing.JLabel();
        panelEditar = new javax.swing.JPanel();
        lEditar = new javax.swing.JLabel();
        panelEliminar = new javax.swing.JPanel();
        lEliminar = new javax.swing.JLabel();
        lNombreCancion = new javax.swing.JLabel();
        lNombreAutor = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelBarraIzq.setBackground(new java.awt.Color(204, 102, 0));
        panelBarraIzq.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelBarraIzqMousePressed(evt);
            }
        });

        lVerHojas.setFont(new java.awt.Font("Segoe UI Light", 0, 36)); // NOI18N
        lVerHojas.setForeground(new java.awt.Color(255, 255, 255));
        lVerHojas.setText("Ver hojas");

        panelSalir.setBackground(new java.awt.Color(204, 204, 204));
        panelSalir.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        panelSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelSalirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelSalirMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelSalirMousePressed(evt);
            }
        });

        lSalir.setBackground(new java.awt.Color(204, 204, 204));
        lSalir.setForeground(new java.awt.Color(0, 0, 0));
        lSalir.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lSalir.setText("Salir");

        javax.swing.GroupLayout panelSalirLayout = new javax.swing.GroupLayout(panelSalir);
        panelSalir.setLayout(panelSalirLayout);
        panelSalirLayout.setHorizontalGroup(
            panelSalirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSalirLayout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addComponent(lSalir)
                .addGap(47, 47, 47))
        );
        panelSalirLayout.setVerticalGroup(
            panelSalirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSalirLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lSalir)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelBarraIzqLayout = new javax.swing.GroupLayout(panelBarraIzq);
        panelBarraIzq.setLayout(panelBarraIzqLayout);
        panelBarraIzqLayout.setHorizontalGroup(
            panelBarraIzqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBarraIzqLayout.createSequentialGroup()
                .addGroup(panelBarraIzqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelBarraIzqLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(panelSalir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelBarraIzqLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(lVerHojas)))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        panelBarraIzqLayout.setVerticalGroup(
            panelBarraIzqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBarraIzqLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(lVerHojas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelSalir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );

        panelBarraDer.setBackground(new java.awt.Color(255, 255, 255));
        panelBarraDer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelBarraDerMousePressed(evt);
            }
        });

        lCancion.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lCancion.setText("Canción");

        lAutor.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lAutor.setText("Autor");

        listaHojas.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        listaHojas.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        listaHojas.setToolTipText("Haga doble clic para visualizar una hoja");
        if(music.getContador()>0){
            for(int i=0; i<music.getContador(); i++){
                modelo.addElement(music.mostrar(i)+"\n");
            }
        }
        listaHojas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listaHojasMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                listaHojasMousePressed(evt);
            }
        });
        scrollpaneListaHojas.setViewportView(listaHojas);

        panelTransportar.setBackground(new java.awt.Color(204, 204, 204));
        panelTransportar.setPreferredSize(new java.awt.Dimension(129, 47));
        panelTransportar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelTransportarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelTransportarMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelTransportarMousePressed(evt);
            }
        });

        lTransportar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lTransportar.setForeground(new java.awt.Color(102, 102, 102));
        lTransportar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lTransportar.setText("Transportar");

        javax.swing.GroupLayout panelTransportarLayout = new javax.swing.GroupLayout(panelTransportar);
        panelTransportar.setLayout(panelTransportarLayout);
        panelTransportarLayout.setHorizontalGroup(
            panelTransportarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lTransportar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
        );
        panelTransportarLayout.setVerticalGroup(
            panelTransportarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransportarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lTransportar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelEditar.setBackground(new java.awt.Color(204, 204, 204));
        panelEditar.setPreferredSize(new java.awt.Dimension(129, 47));
        panelEditar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelEditarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelEditarMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelEditarMousePressed(evt);
            }
        });

        lEditar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lEditar.setForeground(new java.awt.Color(102, 102, 102));
        lEditar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lEditar.setText("Editar");

        javax.swing.GroupLayout panelEditarLayout = new javax.swing.GroupLayout(panelEditar);
        panelEditar.setLayout(panelEditarLayout);
        panelEditarLayout.setHorizontalGroup(
            panelEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lEditar, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
        );
        panelEditarLayout.setVerticalGroup(
            panelEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEditarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lEditar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelEliminar.setBackground(new java.awt.Color(204, 204, 204));
        panelEliminar.setPreferredSize(new java.awt.Dimension(129, 47));
        panelEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelEliminarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelEliminarMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelEliminarMousePressed(evt);
            }
        });

        lEliminar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lEliminar.setForeground(new java.awt.Color(102, 102, 102));
        lEliminar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lEliminar.setText("Eliminar");

        javax.swing.GroupLayout panelEliminarLayout = new javax.swing.GroupLayout(panelEliminar);
        panelEliminar.setLayout(panelEliminarLayout);
        panelEliminarLayout.setHorizontalGroup(
            panelEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
        );
        panelEliminarLayout.setVerticalGroup(
            panelEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEliminarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lEliminar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lNombreCancion.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lNombreCancion.setText("Nombre Cancion");
        lNombreCancion.setText(music.getNombre()+" ");

        lNombreAutor.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lNombreAutor.setText("Nombre Autor");
        lNombreAutor.setText(music.getAutor()+" ");

        javax.swing.GroupLayout panelBarraDerLayout = new javax.swing.GroupLayout(panelBarraDer);
        panelBarraDer.setLayout(panelBarraDerLayout);
        panelBarraDerLayout.setHorizontalGroup(
            panelBarraDerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBarraDerLayout.createSequentialGroup()
                .addContainerGap(43, Short.MAX_VALUE)
                .addGroup(panelBarraDerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelBarraDerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(scrollpaneListaHojas, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelBarraDerLayout.createSequentialGroup()
                            .addComponent(panelTransportar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(panelEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(panelEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelBarraDerLayout.createSequentialGroup()
                        .addGroup(panelBarraDerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lCancion)
                            .addComponent(lNombreCancion, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(88, 88, 88)
                        .addGroup(panelBarraDerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelBarraDerLayout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(lAutor))
                            .addComponent(lNombreAutor, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(34, 34, 34))
        );
        panelBarraDerLayout.setVerticalGroup(
            panelBarraDerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBarraDerLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(panelBarraDerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lCancion)
                    .addComponent(lAutor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelBarraDerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lNombreCancion)
                    .addComponent(lNombreAutor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollpaneListaHojas, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelBarraDerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelTransportar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelBarraIzq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelBarraDer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBarraIzq, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelBarraDer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void panelBarraIzqMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelBarraIzqMousePressed
        listaHojas.clearSelection();
        lTransportar.setForeground(new  java.awt.Color(102,102,102));
        lEditar.setForeground(new  java.awt.Color(102,102,102));
        lEliminar.setForeground(new  java.awt.Color(102,102,102));
    }//GEN-LAST:event_panelBarraIzqMousePressed

    private void panelSalirMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelSalirMousePressed
        InicioFrame frameinicio= new InicioFrame(music);
        frameinicio.setVisible(true);
        this.setVisible(false);	       
    }//GEN-LAST:event_panelSalirMousePressed

    private void panelSalirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelSalirMouseEntered
        panelSalir.setBackground(new  java.awt.Color(216,216,216));
    }//GEN-LAST:event_panelSalirMouseEntered

    private void panelSalirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelSalirMouseExited
        panelSalir.setBackground(new  java.awt.Color(204,204,204));
    }//GEN-LAST:event_panelSalirMouseExited

    private void panelTransportarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelTransportarMouseExited
        if(listaHojas.getSelectedIndex()!=-1){
            panelTransportar.setBackground(new  java.awt.Color(204,204,204));
            lTransportar.setForeground(new  java.awt.Color(0,0,0));
        }
    }//GEN-LAST:event_panelTransportarMouseExited

    private void panelBarraDerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelBarraDerMousePressed
        listaHojas.clearSelection();
        lTransportar.setForeground(new  java.awt.Color(102,102,102));
        lEditar.setForeground(new  java.awt.Color(102,102,102));
        lEliminar.setForeground(new  java.awt.Color(102,102,102));
    }//GEN-LAST:event_panelBarraDerMousePressed

    private void panelTransportarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelTransportarMouseEntered
        
        if(listaHojas.getSelectedIndex()!=-1){
            panelTransportar.setBackground(new  java.awt.Color(216,216,216));
            lTransportar.setForeground(new  java.awt.Color(0,0,0));
        }
    }//GEN-LAST:event_panelTransportarMouseEntered

    private void listaHojasMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listaHojasMousePressed
        if(listaHojas.getSelectedIndex()!=-1){
            lTransportar.setForeground(new  java.awt.Color(0,0,0));
            lEditar.setForeground(new  java.awt.Color(0,0,0));
            lEliminar.setForeground(new  java.awt.Color(0,0,0));
        }
    }//GEN-LAST:event_listaHojasMousePressed

    private void panelTransportarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelTransportarMousePressed
        if(listaHojas.getSelectedIndex()!=-1){
            TransportarFrame frametransportar= new TransportarFrame(music,listaHojas.getSelectedIndex());
            frametransportar.setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_panelTransportarMousePressed

    private void panelEditarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelEditarMousePressed
        if(listaHojas.getSelectedIndex()!=-1){
            EditarFrame frameeditar= new EditarFrame(music,listaHojas.getSelectedIndex());
            frameeditar.setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_panelEditarMousePressed

    private void panelEditarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelEditarMouseEntered
        if(listaHojas.getSelectedIndex()!=-1){
            panelEditar.setBackground(new  java.awt.Color(216,216,216));
            lEditar.setForeground(new  java.awt.Color(0,0,0));
        }
    }//GEN-LAST:event_panelEditarMouseEntered

    private void panelEditarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelEditarMouseExited
        if(listaHojas.getSelectedIndex()!=-1){
            panelEditar.setBackground(new  java.awt.Color(204,204,204));
            lEditar.setForeground(new  java.awt.Color(0,0,0));
        }
    }//GEN-LAST:event_panelEditarMouseExited

    private void panelEliminarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelEliminarMouseEntered
        if(listaHojas.getSelectedIndex()!=-1){
            panelEliminar.setBackground(new  java.awt.Color(216,216,216));
            lEliminar.setForeground(new  java.awt.Color(0,0,0));
        }
    }//GEN-LAST:event_panelEliminarMouseEntered

    private void panelEliminarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelEliminarMouseExited
        if(listaHojas.getSelectedIndex()!=-1){
            panelEliminar.setBackground(new  java.awt.Color(204,204,204));
            lEliminar.setForeground(new  java.awt.Color(0,0,0));
        }
    }//GEN-LAST:event_panelEliminarMouseExited

    private void panelEliminarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelEliminarMousePressed
        
        if(listaHojas.getSelectedIndex()!=-1){
            int respuesta=JOptionPane.showConfirmDialog(null, "¿Realmente desea eliminar esta hoja?");
            if(respuesta==0){
                int indice= listaHojas.getSelectedIndex();
                modelo.clear();
                music.eliminarhoja(indice);

                if(music.getContador()>0){
                    for(int i=0; i<music.getContador(); i++){
                        modelo.addElement(music.mostrar(i));
                        listaHojas.setModel(modelo);
                        listaHojas.ensureIndexIsVisible(modelo.getSize());
                    }
                }
                lTransportar.setForeground(new  java.awt.Color(102,102,102));
                lEditar.setForeground(new  java.awt.Color(102,102,102));
                lEliminar.setForeground(new  java.awt.Color(102,102,102));
            }
        }
        
    }//GEN-LAST:event_panelEliminarMousePressed

    private void listaHojasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listaHojasMouseClicked
        if (evt.getClickCount() == 2) { //Doble clic detectado
            int index = listaHojas.locationToIndex(evt.getPoint()); //Obtiene el lugar donde se hizo clic
            VisualizarFrame framevisualizar= new VisualizarFrame(music,listaHojas.getSelectedIndex());
            framevisualizar.setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_listaHojasMouseClicked
    
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VerHojasFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VerHojasFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VerHojasFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VerHojasFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VerHojasFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lAutor;
    private javax.swing.JLabel lCancion;
    private javax.swing.JLabel lEditar;
    private javax.swing.JLabel lEliminar;
    public javax.swing.JLabel lNombreAutor;
    public javax.swing.JLabel lNombreCancion;
    private javax.swing.JLabel lSalir;
    private javax.swing.JLabel lTransportar;
    private javax.swing.JLabel lVerHojas;
    public javax.swing.JList<String> listaHojas;
    private javax.swing.JPanel panelBarraDer;
    private javax.swing.JPanel panelBarraIzq;
    public javax.swing.JPanel panelEditar;
    public javax.swing.JPanel panelEliminar;
    public javax.swing.JPanel panelSalir;
    public javax.swing.JPanel panelTransportar;
    private javax.swing.JScrollPane scrollpaneListaHojas;
    // End of variables declaration//GEN-END:variables
}
