package tonito;

import javax.swing.ImageIcon;

public class VisualizarFrame extends javax.swing.JFrame {

    private HojaMusical music;
    private int posicion=0;
    public VisualizarFrame(HojaMusical cancion, int posicion) {
        music = cancion;
        initComponents();
        setTitle("TonUDO");
        setIconImage(new ImageIcon(getClass().getResource("TonUDOiconoblack-01.png")).getImage());
        setLocationRelativeTo(null);
        setResizable(false);
    }
    public VisualizarFrame(){
        initComponents();
        setTitle("TonUDO");
        setIconImage(new ImageIcon(getClass().getResource("TonUDOiconoblack-01.png")).getImage());
        setLocationRelativeTo(null);
        setResizable(false);        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBarraIzq = new javax.swing.JPanel();
        panelNombreTonoActualyAsterisco = new javax.swing.JPanel();
        lTonoActual = new javax.swing.JLabel();
        tfTonoActual = new javax.swing.JTextField();
        panelbotonsal = new javax.swing.JPanel();
        panelSalir = new javax.swing.JPanel();
        lSalir = new javax.swing.JLabel();
        panelBarraDer = new javax.swing.JPanel();
        lAcordes = new javax.swing.JLabel();
        scrollpaneAcordes = new javax.swing.JScrollPane();
        taAcordes = new javax.swing.JTextArea();
        lNombre = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelBarraIzq.setBackground(new java.awt.Color(255, 255, 255));

        panelNombreTonoActualyAsterisco.setBackground(new java.awt.Color(255, 255, 255));

        lTonoActual.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        lTonoActual.setText("Tono actual");

        tfTonoActual.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tfTonoActual.setEnabled(false);
        tfTonoActual.setText(music.getTonoActualhoja(posicion));

        javax.swing.GroupLayout panelNombreTonoActualyAsteriscoLayout = new javax.swing.GroupLayout(panelNombreTonoActualyAsterisco);
        panelNombreTonoActualyAsterisco.setLayout(panelNombreTonoActualyAsteriscoLayout);
        panelNombreTonoActualyAsteriscoLayout.setHorizontalGroup(
            panelNombreTonoActualyAsteriscoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNombreTonoActualyAsteriscoLayout.createSequentialGroup()
                .addComponent(lTonoActual)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tfTonoActual, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 156, Short.MAX_VALUE))
        );
        panelNombreTonoActualyAsteriscoLayout.setVerticalGroup(
            panelNombreTonoActualyAsteriscoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNombreTonoActualyAsteriscoLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(panelNombreTonoActualyAsteriscoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lTonoActual)
                    .addComponent(tfTonoActual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 32, Short.MAX_VALUE))
        );

        panelbotonsal.setBackground(new java.awt.Color(255, 255, 255));

        panelSalir.setBackground(new java.awt.Color(204, 204, 204));
        panelSalir.setForeground(new java.awt.Color(0, 0, 0));
        panelSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelSalirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelSalirMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelSalirMousePressed(evt);
            }
        });

        lSalir.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lSalir.setForeground(new java.awt.Color(0, 0, 0));
        lSalir.setText("Salir");

        javax.swing.GroupLayout panelSalirLayout = new javax.swing.GroupLayout(panelSalir);
        panelSalir.setLayout(panelSalirLayout);
        panelSalirLayout.setHorizontalGroup(
            panelSalirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSalirLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(lSalir)
                .addContainerGap(32, Short.MAX_VALUE))
        );
        panelSalirLayout.setVerticalGroup(
            panelSalirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSalirLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lSalir)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelbotonsalLayout = new javax.swing.GroupLayout(panelbotonsal);
        panelbotonsal.setLayout(panelbotonsalLayout);
        panelbotonsalLayout.setHorizontalGroup(
            panelbotonsalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelbotonsalLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelSalir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelbotonsalLayout.setVerticalGroup(
            panelbotonsalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelbotonsalLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelSalir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout panelBarraIzqLayout = new javax.swing.GroupLayout(panelBarraIzq);
        panelBarraIzq.setLayout(panelBarraIzqLayout);
        panelBarraIzqLayout.setHorizontalGroup(
            panelBarraIzqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBarraIzqLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelBarraIzqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelbotonsal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelNombreTonoActualyAsterisco, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelBarraIzqLayout.setVerticalGroup(
            panelBarraIzqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBarraIzqLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelNombreTonoActualyAsterisco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelbotonsal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );

        panelBarraDer.setBackground(new java.awt.Color(102, 102, 102));

        lAcordes.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        lAcordes.setForeground(new java.awt.Color(255, 255, 255));
        lAcordes.setText("Acordes");

        scrollpaneAcordes.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        scrollpaneAcordes.setAutoscrolls(true);

        taAcordes.setColumns(20);
        taAcordes.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        taAcordes.setLineWrap(true);
        taAcordes.setRows(5);
        taAcordes.setEnabled(false);
        taAcordes.setText(music.getAcordeshoja(posicion));
        scrollpaneAcordes.setViewportView(taAcordes);

        lNombre.setBackground(new java.awt.Color(102, 102, 102));
        lNombre.setFont(new java.awt.Font("Segoe UI Light", 0, 36)); // NOI18N
        lNombre.setForeground(new java.awt.Color(255, 255, 255));
        lNombre.setText("  ");
        lNombre.setText(music.getNombrehoja(posicion));

        javax.swing.GroupLayout panelBarraDerLayout = new javax.swing.GroupLayout(panelBarraDer);
        panelBarraDer.setLayout(panelBarraDerLayout);
        panelBarraDerLayout.setHorizontalGroup(
            panelBarraDerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBarraDerLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(panelBarraDerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(scrollpaneAcordes, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 292, Short.MAX_VALUE)
                    .addComponent(lAcordes, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lNombre, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        panelBarraDerLayout.setVerticalGroup(
            panelBarraDerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBarraDerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lNombre)
                .addGap(1, 1, 1)
                .addComponent(lAcordes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(scrollpaneAcordes, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelBarraDer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelBarraIzq, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBarraIzq, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelBarraDer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void panelSalirMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelSalirMousePressed
        VerHojasFrame frameverhojas= new VerHojasFrame(music);
        frameverhojas.setVisible(true);
        this.setVisible(false);// TODO add your handling code here:
    }//GEN-LAST:event_panelSalirMousePressed

    private void panelSalirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelSalirMouseEntered
        panelSalir.setBackground(new  java.awt.Color(216,216,216));// TODO add your handling code here:
    }//GEN-LAST:event_panelSalirMouseEntered

    private void panelSalirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelSalirMouseExited
        panelSalir.setBackground(new  java.awt.Color(204,204,204));// TODO add your handling code here:
    }//GEN-LAST:event_panelSalirMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VisualizarFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VisualizarFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VisualizarFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VisualizarFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VisualizarFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lAcordes;
    public javax.swing.JLabel lNombre;
    private javax.swing.JLabel lSalir;
    private javax.swing.JLabel lTonoActual;
    private javax.swing.JPanel panelBarraDer;
    private javax.swing.JPanel panelBarraIzq;
    private javax.swing.JPanel panelNombreTonoActualyAsterisco;
    public javax.swing.JPanel panelSalir;
    private javax.swing.JPanel panelbotonsal;
    private javax.swing.JScrollPane scrollpaneAcordes;
    public javax.swing.JTextArea taAcordes;
    public javax.swing.JTextField tfTonoActual;
    // End of variables declaration//GEN-END:variables
}
